# ZF / 美债期货期权链调试 notebook

这个 notebook 用 `ib_async` 逐步调试：连接 IB Gateway、枚举多个底层期货月份的 FOP 期权链、分批 qualify、并发订阅报价 / OI / 成交量 / Greeks。

关键点：不要只查 `ZF2606` 一个底层 conId。临近到期时，`ZF2606` 下面可能只剩少量期权到期日，后续日期通常挂在 `ZF2609`、`ZF2612` 等后续底层期货合约上。

In [2]:
from ib_async import IB, util
import pandas as pd
from pathlib import Path
import random

from treasury_fop_chain import (
    attach_error_collector,
    detach_error_collector,
    discover_future_months,
    qualify_future,
    get_future_price,
    get_future_prices_for_months,
    get_reference_price,
    build_treasury_fop_universe,
    save_universe,
    load_universe,
    FOPMarketDataStreamer,
    snapshot_in_batches,
    select_atm_contracts,
    filter_contracts_by_moneyness,
    prepare_snapshot_features,
    summarize_snapshot,
)

util.startLoop()
pd.set_option("display.max_columns", 160)
pd.set_option("display.width", 240)

## 1. 参数

`FUTURE_MONTHS` 是最重要的参数。比如当前要完整覆盖 ZF 期权，不要只填 `202606`，而是把后续活跃底层月份一起填上。

In [3]:
ROOT = "ZF"
FUTURE_MONTHS = ["202606", "202609", "202612"]

HOST = "127.0.0.1"
PORT = 4002          # IB Gateway paper: 4002; live: 4001; TWS paper: 7497
CLIENT_ID = random.randint(2000, 9999)
MARKET_DATA_TYPE = 1 # 1=live, 2=frozen, 3=delayed, 4=delayed frozen

UNIVERSE_CSV = Path(f"{ROOT}_FOP_Universe_{'_'.join(FUTURE_MONTHS)}.csv")
SNAPSHOT_CSV = Path(f"{ROOT}_FOP_Snapshot.csv")

ROOT, FUTURE_MONTHS, CLIENT_ID, UNIVERSE_CSV

('ZF',
 ['202606', '202609', '202612'],
 3902,
 WindowsPath('ZF_FOP_Universe_202606_202609_202612.csv'))

## 2. 连接 IB Gateway

如果看到 `10197`，通常是其他终端正在抢实时行情权限；如果看到 `354`，通常是没有对应市场数据订阅。

In [ ]:
ib = IB()
ib.connect(HOST, PORT, clientId=CLIENT_ID, timeout=10)
ib.reqMarketDataType(MARKET_DATA_TYPE)
errors, error_handler = attach_error_collector(ib)

print("connected:", ib.isConnected(), "clientId:", CLIENT_ID)

connected: True clientId: 3902

Error 10197, reqId 4: No market data during competing live session, contract: Future(conId=818615223, symbol='ZF', lastTradeDateOrContractMonth='20260630', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZFM6', tradingClass='ZF')

[IB error] 10197: No market data during competing live session

Error 200, reqId 1299: No security definition has been found for the request, contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=88.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Error 200, reqId 1300: No security definition has been found for the request, contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=88.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Error 200, reqId 1301: No security definition has been found for the request, contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=88.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')

[IB error] 200: No security definition has been found for the request
[IB error] 200: No security definition has been found for the request
[IB error] 200: No security definition has been found for the request

Error 200, reqId 1302: No security definition has been found for the request, contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=88.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')

[IB error] 200: No security definition has been found for the request

Error 200, reqId 1443: No security definition has been found for the request, contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=116.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Error 200, reqId 1444: No security definition has been found for the request, contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=116.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Error 200, reqId 1445: No security definition has been found for the request, contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=116.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Error 200, reqId 1446: No security definition has been found for the request, contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=116.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Error 200, reqId 1448: No security definition has been found for the request, contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=117.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')

[IB error] 200: No security definition has been found for the request
[IB error] 200: No security definition has been found for the request
[IB error] 200: No security definition has been found for the request
[IB error] 200: No security definition has been found for the request

Error 200, reqId 1447: No security definition has been found for the request, contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=117.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Error 200, reqId 1449: No security definition has been found for the request, contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=117.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Error 200, reqId 1450: No security definition has been found for the request, contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=117.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Error 200, reqId 1451: No security definition has been found for the request, contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=117.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Error 200, reqId 1452: No security definition has been found for the request, contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=117.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Error 200, reqId 1453: No security definition has been found for the request, contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=88.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Error 200, reqId 1454: No security definition has been found for the request, contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=88.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Error 200, reqId 1456: No security definition has been found for the request, contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=88.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Error 200, reqId 1455: No security definition has been found for the request, contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=88.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')

[IB error] 200: No security definition has been found for the request
[IB error] 200: No security definition has been found for the request
[IB error] 200: No security definition has been found for the request
[IB error] 200: No security definition has been found for the request
[IB error] 200: No security definition has been found for the request
[IB error] 200: No security definition has been found for the request
[IB error] 200: No security definition has been found for the request
[IB error] 200: No security definition has been found for the request
[IB error] 200: No security definition has been found for the request
[IB error] 200: No security definition has been found for the request

Error 200, reqId 1745: No security definition has been found for the request, contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=116.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Error 200, reqId 1746: No security definition has been found for the request, contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=116.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')

[IB error] 200: No security definition has been found for the request
[IB error] 200: No security definition has been found for the request

Error 1100, reqId -1: Connectivity between IBKR and Trader Workstation has been lost.
Error 1102, reqId -1: Connectivity between IBKR and Trader Workstation has been restored - data maintained. The following farms are connected: hfarm; usfuture; secdefhk. The following farms are not connected: apachmds.
Error 10197, reqId 2772: No market data during competing live session, contract: Contract(secType='FOP', conId=877321915, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=106.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 C1067', tradingClass='OZF')
Error 10197, reqId 2030: No market data during competing live session, contract: Contract(secType='FOP', conId=883636291, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=105.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 P1052', tradingClass='HF4')
Error 10197, reqId 2514: No market data during competing live session, contract: Contract(secType='FOP', conId=884607176, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=106.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1062', tradingClass='ZF2')
Error 10197, reqId 2198: No market data during competing live session, contract: Contract(secType='FOP', conId=885029160, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=107.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 C1072', tradingClass='GF1')
Error 10197, reqId 1921: No market data during competing live session, contract: Contract(secType='FOP', conId=882370089, symbol='ZF', lastTradeDateOrContractMonth='20260526', strike=108.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF4K6 P1080', tradingClass='GF4')
Error 10197, reqId 2846: No market data during competing live session, contract: Contract(secType='FOP', conId=870223110, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=109.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 C1092', tradingClass='OZF')
Error 10197, reqId 2507: No market data during competing live session, contract: Contract(secType='FOP', conId=884607312, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=104.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1045', tradingClass='ZF2')
Error 10197, reqId 2268: No market data during competing live session, contract: Contract(secType='FOP', conId=885310344, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=108.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 C1087', tradingClass='WF1')
Error 10197, reqId 1967: No market data during competing live session, contract: Contract(secType='FOP', conId=882727324, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=105.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 P1055', tradingClass='WF4')
Error 10197, reqId 2416: No market data during competing live session, contract: Contract(secType='FOP', conId=881572460, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=105.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 P1057', tradingClass='ZF1')
Error 10197, reqId 2305: No market data during competing live session, contract: Contract(secType='FOP', conId=885310218, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=110.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 P1100', tradingClass='WF1')
Error 10197, reqId 2771: No market data during competing live session, contract: Contract(secType='FOP', conId=877321869, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=106.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 C1065', tradingClass='OZF')
Error 10197, reqId 1949: No market data during competing live session, contract: Contract(secType='FOP', conId=882727547, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=109.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 C1090', tradingClass='WF4')
Error 10197, reqId 1946: No market data during competing live session, contract: Contract(secType='FOP', conId=882727510, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=108.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 C1082', tradingClass='WF4')
Error 10197, reqId 2531: No market data during competing live session, contract: Contract(secType='FOP', conId=884607167, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=110.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1105', tradingClass='ZF2')
Error 10197, reqId 2449: No market data during competing live session, contract: Contract(secType='FOP', conId=884728466, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=106.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1060', tradingClass='VF2')
Error 10197, reqId 2063: No market data during competing live session, contract: Contract(secType='FOP', conId=879598755, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=105.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 C1055', tradingClass='ZF5')
Error 10197, reqId 2585: No market data during competing live session, contract: Contract(secType='FOP', conId=849163248, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=108.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 C1080', tradingClass='OZF')
Error 10197, reqId 2652: No market data during competing live session, contract: Contract(secType='FOP', conId=869662931, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=108.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 C1087', tradingClass='OZF')
Error 10197, reqId 2522: No market data during competing live session, contract: Contract(secType='FOP', conId=884607412, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=108.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1082', tradingClass='ZF2')
Error 10197, reqId 2106: No market data during competing live session, contract: Contract(secType='FOP', conId=879598724, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=108.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 P1082', tradingClass='ZF5')
Error 10197, reqId 2509: No market data during competing live session, contract: Contract(secType='FOP', conId=884607094, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=105.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1050', tradingClass='ZF2')
Error 10197, reqId 2657: No market data during competing live session, contract: Contract(secType='FOP', conId=869663204, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=110.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 C1100', tradingClass='OZF')
Error 10197, reqId 2600: No market data during competing live session, contract: Contract(secType='FOP', conId=849162889, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=103.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 P1037', tradingClass='OZF')
Error 10197, reqId 2387: No market data during competing live session, contract: Contract(secType='FOP', conId=881572568, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=106.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 C1065', tradingClass='ZF1')
Error 10197, reqId 2447: No market data during competing live session, contract: Contract(secType='FOP', conId=884728381, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=105.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1055', tradingClass='VF2')
Error 10197, reqId 2438: No market data during competing live session, contract: Contract(secType='FOP', conId=884728471, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=103.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1032', tradingClass='VF2')
Error 10197, reqId 2516: No market data during competing live session, contract: Contract(secType='FOP', conId=884607133, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=106.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1067', tradingClass='ZF2')
Error 10197, reqId 2695: No market data during competing live session, contract: Contract(secType='FOP', conId=842944635, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=103.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 C1035', tradingClass='OZF')
Error 10197, reqId 2556: No market data during competing live session, contract: Contract(secType='FOP', conId=884607230, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=108.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 P1087', tradingClass='ZF2')
Error 10197, reqId 2399: No market data during competing live session, contract: Contract(secType='FOP', conId=881572293, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=109.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 C1095', tradingClass='ZF1')
Error 10197, reqId 2428: No market data during competing live session, contract: Contract(secType='FOP', conId=881572562, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=108.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 P1087', tradingClass='ZF1')
Error 10197, reqId 2176: No market data during competing live session, contract: Contract(secType='FOP', conId=881986125, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=109.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 P1097', tradingClass='VF1')
Error 10197, reqId 2801: No market data during competing live session, contract: Contract(secType='FOP', conId=877321893, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=106.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 P1060', tradingClass='OZF')
Error 10197, reqId 2186: No market data during competing live session, contract: Contract(secType='FOP', conId=885028807, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=104.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 C1042', tradingClass='GF1')
Error 10197, reqId 2597: No market data during competing live session, contract: Contract(secType='FOP', conId=849162933, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=103.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 P1030', tradingClass='OZF')
Error 10197, reqId 2410: No market data during competing live session, contract: Contract(secType='FOP', conId=881572488, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=104.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 P1042', tradingClass='ZF1')
Error 10197, reqId 2859: No market data during competing live session, contract: Contract(secType='FOP', conId=870222861, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=104.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 P1045', tradingClass='OZF')
Error 10197, reqId 2667: No market data during competing live session, contract: Contract(secType='FOP', conId=869662824, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=104.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 P1045', tradingClass='OZF')
Error 10197, reqId 2112: No market data during competing live session, contract: Contract(secType='FOP', conId=879598547, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=109.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 P1097', tradingClass='ZF5')
Error 10197, reqId 2343: No market data during competing live session, contract: Contract(secType='FOP', conId=885751775, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=103.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 P1035', tradingClass='HF1')
Error 10197, reqId 2166: No market data during competing live session, contract: Contract(secType='FOP', conId=881985993, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=107.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 P1072', tradingClass='VF1')
Error 10197, reqId 2788: No market data during competing live session, contract: Contract(secType='FOP', conId=877321848, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=110.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 C1107', tradingClass='OZF')
Error 10197, reqId 2645: No market data during competing live session, contract: Contract(secType='FOP', conId=869663075, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=107.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 C1070', tradingClass='OZF')
Error 10197, reqId 2719: No market data during competing live session, contract: Contract(secType='FOP', conId=842944696, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=109.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 C1095', tradingClass='OZF')
Error 10197, reqId 2339: No market data during competing live session, contract: Contract(secType='FOP', conId=885751639, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=110.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 C1105', tradingClass='HF1')
Error 10197, reqId 1957: No market data during competing live session, contract: Contract(secType='FOP', conId=882727433, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=103.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 P1030', tradingClass='WF4')
Error 10197, reqId 1904: No market data during competing live session, contract: Contract(secType='FOP', conId=882370052, symbol='ZF', lastTradeDateOrContractMonth='20260526', strike=107.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF4K6 C1077', tradingClass='GF4')
Error 10197, reqId 2317: No market data during competing live session, contract: Contract(secType='FOP', conId=885751690, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=105.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 C1050', tradingClass='HF1')
Error 10197, reqId 2745: No market data during competing live session, contract: Contract(secType='FOP', conId=842944878, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=108.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 P1080', tradingClass='OZF')
Error 10197, reqId 2262: No market data during competing live session, contract: Contract(secType='FOP', conId=885310276, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=107.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 C1072', tradingClass='WF1')
Error 10197, reqId 2029: No market data during competing live session, contract: Contract(secType='FOP', conId=883636065, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=105.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 P1050', tradingClass='HF4')
Error 10197, reqId 2741: No market data during competing live session, contract: Contract(secType='FOP', conId=842944911, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=107.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 P1070', tradingClass='OZF')
Error 10197, reqId 2346: No market data during competing live session, contract: Contract(secType='FOP', conId=885751559, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=104.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 P1042', tradingClass='HF1')
Error 10197, reqId 2762: No market data during competing live session, contract: Contract(secType='FOP', conId=877322121, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=104.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 C1042', tradingClass='OZF')
Error 10197, reqId 2521: No market data during competing live session, contract: Contract(secType='FOP', conId=884607334, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=108.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1080', tradingClass='ZF2')
Error 10197, reqId 2644: No market data during competing live session, contract: Contract(secType='FOP', conId=869662981, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=106.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 C1067', tradingClass='OZF')
Error 10197, reqId 2796: No market data during competing live session, contract: Contract(secType='FOP', conId=877322105, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=104.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 P1047', tradingClass='OZF')
Error 10197, reqId 2851: No market data during competing live session, contract: Contract(secType='FOP', conId=870222694, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=110.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 C1105', tradingClass='OZF')
Error 10197, reqId 2554: No market data during competing live session, contract: Contract(secType='FOP', conId=884607442, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=108.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 P1082', tradingClass='ZF2')
Error 10197, reqId 2174: No market data during competing live session, contract: Contract(secType='FOP', conId=881985990, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=109.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 P1092', tradingClass='VF1')
Error 10197, reqId 2099: No market data during competing live session, contract: Contract(secType='FOP', conId=879598575, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=106.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 P1065', tradingClass='ZF5')
Error 10197, reqId 2737: No market data during competing live session, contract: Contract(secType='FOP', conId=842944721, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=106.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 P1060', tradingClass='OZF')
Error 10197, reqId 2813: No market data during competing live session, contract: Contract(secType='FOP', conId=877321878, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=109.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 P1090', tradingClass='OZF')
Error 10197, reqId 2318: No market data during competing live session, contract: Contract(secType='FOP', conId=885751560, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=105.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 C1052', tradingClass='HF1')

[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session

Error 10197, reqId 2658: No market data during competing live session, contract: Contract(secType='FOP', conId=869663106, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=110.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 C1102', tradingClass='OZF')
Error 10197, reqId 2755: No market data during competing live session, contract: Contract(secType='FOP', conId=842944584, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=110.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 P1105', tradingClass='OZF')
Error 10197, reqId 2115: No market data during competing live session, contract: Contract(secType='FOP', conId=879598829, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=110.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 P1105', tradingClass='ZF5')
Error 10197, reqId 2077: No market data during competing live session, contract: Contract(secType='FOP', conId=879598522, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=109.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 C1090', tradingClass='ZF5')
Error 10197, reqId 2625: No market data during competing live session, contract: Contract(secType='FOP', conId=849163271, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=110.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 P1100', tradingClass='OZF')
Error 10197, reqId 2022: No market data during competing live session, contract: Contract(secType='FOP', conId=883636176, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=103.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 P1032', tradingClass='HF4')
Error 10197, reqId 2882: No market data during competing live session, contract: Contract(secType='FOP', conId=870222847, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=110.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 P1102', tradingClass='OZF')
Error 10197, reqId 2177: No market data during competing live session, contract: Contract(secType='FOP', conId=881986017, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=110.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 P1100', tradingClass='VF1')
Error 10197, reqId 2279: No market data during competing live session, contract: Contract(secType='FOP', conId=885310286, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=103.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 P1035', tradingClass='WF1')
Error 10197, reqId 2311: No market data during competing live session, contract: Contract(secType='FOP', conId=885751580, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=103.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 C1035', tradingClass='HF1')
Error 10197, reqId 2160: No market data during competing live session, contract: Contract(secType='FOP', conId=881986101, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=105.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 P1057', tradingClass='VF1')
Error 10197, reqId 2701: No market data during competing live session, contract: Contract(secType='FOP', conId=842944868, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=105.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 C1050', tradingClass='OZF')
Error 10197, reqId 2831: No market data during competing live session, contract: Contract(secType='FOP', conId=870222652, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=105.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 C1055', tradingClass='OZF')
Error 10197, reqId 2275: No market data during competing live session, contract: Contract(secType='FOP', conId=885310213, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=110.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 C1105', tradingClass='WF1')
Error 10197, reqId 2342: No market data during competing live session, contract: Contract(secType='FOP', conId=885751515, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=103.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 P1032', tradingClass='HF1')
Error 10197, reqId 2875: No market data during competing live session, contract: Contract(secType='FOP', conId=870223003, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=108.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 P1085', tradingClass='OZF')
Error 10197, reqId 2334: No market data during competing live session, contract: Contract(secType='FOP', conId=885751745, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=109.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 C1092', tradingClass='HF1')
Error 10197, reqId 2201: No market data during competing live session, contract: Contract(secType='FOP', conId=885029159, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=108.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 C1080', tradingClass='GF1')
Error 10197, reqId 2780: No market data during competing live session, contract: Contract(secType='FOP', conId=877321864, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=108.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 C1087', tradingClass='OZF')
Error 10197, reqId 2640: No market data during competing live session, contract: Contract(secType='FOP', conId=869663216, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=105.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 C1057', tradingClass='OZF')
Error 10197, reqId 2751: No market data during competing live session, contract: Contract(secType='FOP', conId=842944661, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=109.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 P1095', tradingClass='OZF')
Error 10197, reqId 2406: No market data during competing live session, contract: Contract(secType='FOP', conId=881572274, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=103.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 P1032', tradingClass='ZF1')
Error 10197, reqId 2332: No market data during competing live session, contract: Contract(secType='FOP', conId=885751589, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=108.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 C1087', tradingClass='HF1')
Error 10197, reqId 2815: No market data during competing live session, contract: Contract(secType='FOP', conId=877322019, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=109.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 P1095', tradingClass='OZF')
Error 10197, reqId 2205: No market data during competing live session, contract: Contract(secType='FOP', conId=885029001, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=109.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 C1090', tradingClass='GF1')
Error 10197, reqId 2641: No market data during competing live session, contract: Contract(secType='FOP', conId=869662857, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=106.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 C1060', tradingClass='OZF')
Error 10197, reqId 2864: No market data during competing live session, contract: Contract(secType='FOP', conId=870223071, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=105.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 P1057', tradingClass='OZF')
Error 10197, reqId 2285: No market data during competing live session, contract: Contract(secType='FOP', conId=885310322, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=105.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 P1050', tradingClass='WF1')
Error 10197, reqId 2829: No market data during competing live session, contract: Contract(secType='FOP', conId=870222739, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=105.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 C1050', tradingClass='OZF')
Error 10197, reqId 2143: No market data during competing live session, contract: Contract(secType='FOP', conId=881986144, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=109.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 C1095', tradingClass='VF1')
Error 10197, reqId 2431: No market data during competing live session, contract: Contract(secType='FOP', conId=881572245, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=109.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 P1095', tradingClass='ZF1')
Error 10197, reqId 2451: No market data during competing live session, contract: Contract(secType='FOP', conId=884728414, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=106.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1065', tradingClass='VF2')
Error 10197, reqId 2195: No market data during competing live session, contract: Contract(secType='FOP', conId=885028875, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=106.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 C1065', tradingClass='GF1')
Error 10197, reqId 1982: No market data during competing live session, contract: Contract(secType='FOP', conId=882727608, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=109.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 P1092', tradingClass='WF4')
Error 10197, reqId 2675: No market data during competing live session, contract: Contract(secType='FOP', conId=869663061, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=106.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 P1065', tradingClass='OZF')
Error 10197, reqId 2467: No market data during competing live session, contract: Contract(secType='FOP', conId=884728123, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=110.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1105', tradingClass='VF2')
Error 10197, reqId 2243: No market data during competing live session, contract: Contract(secType='FOP', conId=885029035, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=110.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 P1105', tradingClass='GF1')
Error 10197, reqId 2326: No market data during competing live session, contract: Contract(secType='FOP', conId=885751485, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=107.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 C1072', tradingClass='HF1')
Error 10197, reqId 2655: No market data during competing live session, contract: Contract(secType='FOP', conId=869662993, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=109.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 C1095', tradingClass='OZF')
Error 10197, reqId 2502: No market data during competing live session, contract: Contract(secType='FOP', conId=884607215, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=103.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1032', tradingClass='ZF2')
Error 10197, reqId 2553: No market data during competing live session, contract: Contract(secType='FOP', conId=884607337, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=108.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 P1080', tradingClass='ZF2')
Error 10197, reqId 2193: No market data during competing live session, contract: Contract(secType='FOP', conId=885029021, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=106.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 C1060', tradingClass='GF1')
Error 10197, reqId 2037: No market data during competing live session, contract: Contract(secType='FOP', conId=883636215, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=107.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 P1070', tradingClass='HF4')
Error 10197, reqId 1966: No market data during competing live session, contract: Contract(secType='FOP', conId=882727348, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=105.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 P1052', tradingClass='WF4')
Error 10197, reqId 2088: No market data during competing live session, contract: Contract(secType='FOP', conId=879598761, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=103.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 P1037', tradingClass='ZF5')
Error 10197, reqId 2530: No market data during competing live session, contract: Contract(secType='FOP', conId=884607116, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=110.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1102', tradingClass='ZF2')
Error 10197, reqId 1976: No market data during competing live session, contract: Contract(secType='FOP', conId=882727287, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=107.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 P1077', tradingClass='WF4')
Error 10197, reqId 2306: No market data during competing live session, contract: Contract(secType='FOP', conId=885310238, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=110.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 P1102', tradingClass='WF1')
Error 10197, reqId 2619: No market data during competing live session, contract: Contract(secType='FOP', conId=849162972, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=108.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 P1085', tradingClass='OZF')
Error 10197, reqId 2175: No market data during competing live session, contract: Contract(secType='FOP', conId=881986174, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=109.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 P1095', tradingClass='VF1')
Error 10197, reqId 2474: No market data during competing live session, contract: Contract(secType='FOP', conId=884728401, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=104.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 P1042', tradingClass='VF2')
Error 10197, reqId 1980: No market data during competing live session, contract: Contract(secType='FOP', conId=882727318, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=108.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 P1087', tradingClass='WF4')
Error 10197, reqId 2503: No market data during competing live session, contract: Contract(secType='FOP', conId=884607266, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=103.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1035', tradingClass='ZF2')
Error 10197, reqId 2179: No market data during competing live session, contract: Contract(secType='FOP', conId=881986007, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=110.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 P1105', tradingClass='VF1')
Error 10197, reqId 2061: No market data during competing live session, contract: Contract(secType='FOP', conId=879598510, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=105.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 C1050', tradingClass='ZF5')
Error 10197, reqId 2269: No market data during competing live session, contract: Contract(secType='FOP', conId=885310076, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=109.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 C1090', tradingClass='WF1')
Error 10197, reqId 2470: No market data during competing live session, contract: Contract(secType='FOP', conId=884728300, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=103.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 P1032', tradingClass='VF2')
Error 10197, reqId 2529: No market data during competing live session, contract: Contract(secType='FOP', conId=884607196, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=110.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1100', tradingClass='ZF2')
Error 10197, reqId 2876: No market data during competing live session, contract: Contract(secType='FOP', conId=870223041, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=108.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 P1087', tradingClass='OZF')
Error 10197, reqId 2779: No market data during competing live session, contract: Contract(secType='FOP', conId=877321779, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=108.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 C1085', tradingClass='OZF')
Error 10197, reqId 2308: No market data during competing live session, contract: Contract(secType='FOP', conId=885310021, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=110.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 P1107', tradingClass='WF1')
Error 10197, reqId 1945: No market data during competing live session, contract: Contract(secType='FOP', conId=882727556, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=108.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 C1080', tradingClass='WF4')
Error 10197, reqId 2870: No market data during competing live session, contract: Contract(secType='FOP', conId=870222945, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=107.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 P1072', tradingClass='OZF')
Error 10197, reqId 2091: No market data during competing live session, contract: Contract(secType='FOP', conId=879598590, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=104.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 P1045', tradingClass='ZF5')
Error 10197, reqId 2393: No market data during competing live session, contract: Contract(secType='FOP', conId=881572517, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=108.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 C1080', tradingClass='ZF1')
Error 10197, reqId 1918: No market data during competing live session, contract: Contract(secType='FOP', conId=882370242, symbol='ZF', lastTradeDateOrContractMonth='20260526', strike=107.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF4K6 P1072', tradingClass='GF4')

[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session

Error 10197, reqId 2340: No market data during competing live session, contract: Contract(secType='FOP', conId=885751565, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=110.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 C1107', tradingClass='HF1')
Error 10197, reqId 1932: No market data during competing live session, contract: Contract(secType='FOP', conId=882727358, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=104.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 C1047', tradingClass='WF4')
Error 10197, reqId 1907: No market data during competing live session, contract: Contract(secType='FOP', conId=882370152, symbol='ZF', lastTradeDateOrContractMonth='20260526', strike=108.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF4K6 C1085', tradingClass='GF4')
Error 10197, reqId 1929: No market data during competing live session, contract: Contract(secType='FOP', conId=882727661, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=104.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 C1040', tradingClass='WF4')
Error 10197, reqId 2706: No market data during competing live session, contract: Contract(secType='FOP', conId=842944744, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=106.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 C1062', tradingClass='OZF')
Error 10197, reqId 2760: No market data during competing live session, contract: Contract(secType='FOP', conId=877322010, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=103.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 C1037', tradingClass='OZF')
Error 10197, reqId 2563: No market data during competing live session, contract: Contract(secType='FOP', conId=884607407, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=110.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 P1105', tradingClass='ZF2')
Error 10197, reqId 2228: No market data during competing live session, contract: Contract(secType='FOP', conId=885028982, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=106.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 P1067', tradingClass='GF1')
Error 10197, reqId 2047: No market data during competing live session, contract: Contract(secType='FOP', conId=883636150, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=109.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 P1095', tradingClass='HF4')
Error 10197, reqId 2351: No market data during competing live session, contract: Contract(secType='FOP', conId=885751685, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=105.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 P1055', tradingClass='HF1')
Error 10197, reqId 2217: No market data during competing live session, contract: Contract(secType='FOP', conId=885029171, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=104.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 P1040', tradingClass='GF1')
Error 10197, reqId 2203: No market data during competing live session, contract: Contract(secType='FOP', conId=885028789, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=108.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 C1085', tradingClass='GF1')
Error 10197, reqId 2415: No market data during competing live session, contract: Contract(secType='FOP', conId=881572188, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=105.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 P1055', tradingClass='ZF1')
Error 10197, reqId 2338: No market data during competing live session, contract: Contract(secType='FOP', conId=885751455, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=110.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 C1102', tradingClass='HF1')
Error 10197, reqId 2367: No market data during competing live session, contract: Contract(secType='FOP', conId=885751649, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=109.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 P1095', tradingClass='HF1')
Error 10197, reqId 2448: No market data during competing live session, contract: Contract(secType='FOP', conId=884728358, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=105.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1057', tradingClass='VF2')
Error 10197, reqId 1986: No market data during competing live session, contract: Contract(secType='FOP', conId=882727293, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=110.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 P1102', tradingClass='WF4')
Error 10197, reqId 2511: No market data during competing live session, contract: Contract(secType='FOP', conId=884607357, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=105.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1055', tradingClass='ZF2')
Error 10197, reqId 2757: No market data during competing live session, contract: Contract(secType='FOP', conId=877321983, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=103.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 C1030', tradingClass='OZF')
Error 10197, reqId 2348: No market data during competing live session, contract: Contract(secType='FOP', conId=885751545, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=104.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 P1047', tradingClass='HF1')
Error 10197, reqId 2665: No market data during competing live session, contract: Contract(secType='FOP', conId=869663003, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=104.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 P1040', tradingClass='OZF')
Error 10197, reqId 2341: No market data during competing live session, contract: Contract(secType='FOP', conId=885751628, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=103.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 P1030', tradingClass='HF1')
Error 10197, reqId 1950: No market data during competing live session, contract: Contract(secType='FOP', conId=882727345, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=109.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 C1092', tradingClass='WF4')
Error 10197, reqId 2738: No market data during competing live session, contract: Contract(secType='FOP', conId=842944916, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=106.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 P1062', tradingClass='OZF')
Error 10197, reqId 1987: No market data during competing live session, contract: Contract(secType='FOP', conId=882727477, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=110.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 P1105', tradingClass='WF4')
Error 10197, reqId 2814: No market data during competing live session, contract: Contract(secType='FOP', conId=877322039, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=109.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 P1092', tradingClass='OZF')
Error 10197, reqId 2850: No market data during competing live session, contract: Contract(secType='FOP', conId=870223030, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=110.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 C1102', tradingClass='OZF')
Error 10197, reqId 1956: No market data during competing live session, contract: Contract(secType='FOP', conId=882727453, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=110.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 C1107', tradingClass='WF4')
Error 10197, reqId 1926: No market data during competing live session, contract: Contract(secType='FOP', conId=882727366, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=103.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 C1032', tradingClass='WF4')
Error 10197, reqId 2139: No market data during competing live session, contract: Contract(secType='FOP', conId=881985906, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=108.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 C1085', tradingClass='VF1')
Error 10197, reqId 2114: No market data during competing live session, contract: Contract(secType='FOP', conId=879598770, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=110.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 P1102', tradingClass='ZF5')
Error 10197, reqId 2494: No market data during competing live session, contract: Contract(secType='FOP', conId=884728140, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=109.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 P1092', tradingClass='VF2')
Error 10197, reqId 2302: No market data during competing live session, contract: Contract(secType='FOP', conId=885310086, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=109.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 P1092', tradingClass='WF1')
Error 10197, reqId 2795: No market data during competing live session, contract: Contract(secType='FOP', conId=877322015, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=104.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 P1045', tradingClass='OZF')
Error 10197, reqId 2328: No market data during competing live session, contract: Contract(secType='FOP', conId=885751554, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=107.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 C1077', tradingClass='HF1')
Error 10197, reqId 2173: No market data during competing live session, contract: Contract(secType='FOP', conId=881986154, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=109.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 P1090', tradingClass='VF1')
Error 10197, reqId 2452: No market data during competing live session, contract: Contract(secType='FOP', conId=884728249, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=106.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1067', tradingClass='VF2')
Error 10197, reqId 2469: No market data during competing live session, contract: Contract(secType='FOP', conId=884728435, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=103.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 P1030', tradingClass='VF2')
Error 10197, reqId 2696: No market data during competing live session, contract: Contract(secType='FOP', conId=842944709, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=103.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 C1037', tradingClass='OZF')
Error 10197, reqId 1990: No market data during competing live session, contract: Contract(secType='FOP', conId=883635996, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=103.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 C1032', tradingClass='HF4')
Error 10197, reqId 2430: No market data during competing live session, contract: Contract(secType='FOP', conId=881572212, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=109.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 P1092', tradingClass='ZF1')
Error 10197, reqId 1974: No market data during competing live session, contract: Contract(secType='FOP', conId=882727646, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=107.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 P1072', tradingClass='WF4')
Error 10197, reqId 2433: No market data during competing live session, contract: Contract(secType='FOP', conId=881572397, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=110.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 P1100', tradingClass='ZF1')
Error 10197, reqId 2439: No market data during competing live session, contract: Contract(secType='FOP', conId=884728370, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=103.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1035', tradingClass='VF2')
Error 10197, reqId 2158: No market data during competing live session, contract: Contract(secType='FOP', conId=881985972, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=105.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 P1052', tradingClass='VF1')
Error 10197, reqId 2100: No market data during competing live session, contract: Contract(secType='FOP', conId=879598493, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=106.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 P1067', tradingClass='ZF5')
Error 10197, reqId 2777: No market data during competing live session, contract: Contract(secType='FOP', conId=877322145, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=108.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 C1080', tradingClass='OZF')
Error 10197, reqId 2001: No market data during competing live session, contract: Contract(secType='FOP', conId=883636186, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=106.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 C1060', tradingClass='HF4')
Error 10197, reqId 2493: No market data during competing live session, contract: Contract(secType='FOP', conId=884728151, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=109.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 P1090', tradingClass='VF2')
Error 10197, reqId 2746: No market data during competing live session, contract: Contract(secType='FOP', conId=842944885, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=108.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 P1082', tradingClass='OZF')
Error 10197, reqId 2591: No market data during competing live session, contract: Contract(secType='FOP', conId=849162892, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=109.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 C1095', tradingClass='OZF')
Error 10197, reqId 2533: No market data during competing live session, contract: Contract(secType='FOP', conId=884607190, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=103.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 P1030', tradingClass='ZF2')
Error 10197, reqId 1995: No market data during competing live session, contract: Contract(secType='FOP', conId=883636085, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=104.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 C1045', tradingClass='HF4')
Error 10197, reqId 1977: No market data during competing live session, contract: Contract(secType='FOP', conId=882727650, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=108.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 P1080', tradingClass='WF4')
Error 10197, reqId 2011: No market data during competing live session, contract: Contract(secType='FOP', conId=883636226, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=108.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 C1085', tradingClass='HF4')
Error 10197, reqId 2272: No market data during competing live session, contract: Contract(secType='FOP', conId=885310293, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=109.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 C1097', tradingClass='WF1')
Error 10197, reqId 2839: No market data during competing live session, contract: Contract(secType='FOP', conId=870222782, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=107.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 C1075', tradingClass='OZF')
Error 10197, reqId 1979: No market data during competing live session, contract: Contract(secType='FOP', conId=882727406, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=108.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 P1085', tradingClass='WF4')
Error 10197, reqId 1941: No market data during competing live session, contract: Contract(secType='FOP', conId=882727520, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=107.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 C1070', tradingClass='WF4')
Error 10197, reqId 2233: No market data during competing live session, contract: Contract(secType='FOP', conId=885029135, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=108.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 P1080', tradingClass='GF1')
Error 10197, reqId 2697: No market data during competing live session, contract: Contract(secType='FOP', conId=842944684, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=104.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 C1040', tradingClass='OZF')
Error 10197, reqId 2866: No market data during competing live session, contract: Contract(secType='FOP', conId=870222981, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=106.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 P1062', tradingClass='OZF')
Error 10197, reqId 2157: No market data during competing live session, contract: Contract(secType='FOP', conId=881986042, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=105.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 P1050', tradingClass='VF1')
Error 10197, reqId 2537: No market data during competing live session, contract: Contract(secType='FOP', conId=884607181, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=104.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 P1040', tradingClass='ZF2')
Error 10197, reqId 2039: No market data during competing live session, contract: Contract(secType='FOP', conId=883636135, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=107.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 P1075', tradingClass='HF4')
Error 10197, reqId 1951: No market data during competing live session, contract: Contract(secType='FOP', conId=882727607, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=109.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 C1095', tradingClass='WF4')

[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session

Error 10197, reqId 1903: No market data during competing live session, contract: Contract(secType='FOP', conId=882369974, symbol='ZF', lastTradeDateOrContractMonth='20260526', strike=107.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF4K6 C1075', tradingClass='GF4')
Error 10197, reqId 1998: No market data during competing live session, contract: Contract(secType='FOP', conId=883636090, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=105.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 C1052', tradingClass='HF4')
Error 10197, reqId 2825: No market data during competing live session, contract: Contract(secType='FOP', conId=870222921, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=104.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 C1040', tradingClass='OZF')
Error 10197, reqId 2661: No market data during competing live session, contract: Contract(secType='FOP', conId=869662851, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=103.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 P1030', tradingClass='OZF')
Error 10197, reqId 2132: No market data during competing live session, contract: Contract(secType='FOP', conId=881986149, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=106.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 C1067', tradingClass='VF1')
Error 10197, reqId 2690: No market data during competing live session, contract: Contract(secType='FOP', conId=869663156, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=110.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 P1102', tradingClass='OZF')
Error 10197, reqId 2532: No market data during competing live session, contract: Contract(secType='FOP', conId=884607091, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=110.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1107', tradingClass='ZF2')
Error 10197, reqId 2858: No market data during competing live session, contract: Contract(secType='FOP', conId=870222975, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=104.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 P1042', tradingClass='OZF')
Error 10197, reqId 2225: No market data during competing live session, contract: Contract(secType='FOP', conId=885029081, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=106.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 P1060', tradingClass='GF1')
Error 10197, reqId 2835: No market data during competing live session, contract: Contract(secType='FOP', conId=870222941, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=106.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 C1065', tradingClass='OZF')
Error 10197, reqId 2196: No market data during competing live session, contract: Contract(secType='FOP', conId=885029069, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=106.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 C1067', tradingClass='GF1')
Error 10197, reqId 2074: No market data during competing live session, contract: Contract(secType='FOP', conId=879598835, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=108.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 C1082', tradingClass='ZF5')
Error 10197, reqId 2376: No market data during competing live session, contract: Contract(secType='FOP', conId=881572268, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=103.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 C1037', tradingClass='ZF1')
Error 10197, reqId 2391: No market data during competing live session, contract: Contract(secType='FOP', conId=881572222, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=107.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 C1075', tradingClass='ZF1')
Error 10197, reqId 2170: No market data during competing live session, contract: Contract(secType='FOP', conId=881986077, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=108.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 P1082', tradingClass='VF1')
Error 10197, reqId 2820: No market data during competing live session, contract: Contract(secType='FOP', conId=877321724, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=110.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 P1107', tradingClass='OZF')
Error 10197, reqId 2617: No market data during competing live session, contract: Contract(secType='FOP', conId=849163168, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=108.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 P1080', tradingClass='OZF')
Error 10197, reqId 2226: No market data during competing live session, contract: Contract(secType='FOP', conId=885028878, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=106.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 P1062', tradingClass='GF1')
Error 10197, reqId 2621: No market data during competing live session, contract: Contract(secType='FOP', conId=849163195, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=109.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 P1090', tradingClass='OZF')
Error 10197, reqId 1925: No market data during competing live session, contract: Contract(secType='FOP', conId=882727343, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=103.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 C1030', tradingClass='WF4')
Error 10197, reqId 2571: No market data during competing live session, contract: Contract(secType='FOP', conId=849163018, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=104.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 C1045', tradingClass='OZF')
Error 10197, reqId 2861: No market data during competing live session, contract: Contract(secType='FOP', conId=870222711, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=105.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 P1050', tradingClass='OZF')
Error 10197, reqId 2379: No market data during competing live session, contract: Contract(secType='FOP', conId=881572477, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=104.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 C1045', tradingClass='ZF1')
Error 10197, reqId 2748: No market data during competing live session, contract: Contract(secType='FOP', conId=842944719, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=108.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 P1087', tradingClass='OZF')
Error 10197, reqId 2121: No market data during competing live session, contract: Contract(secType='FOP', conId=881985928, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=104.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 C1040', tradingClass='VF1')
Error 10197, reqId 2604: No market data during competing live session, contract: Contract(secType='FOP', conId=849163178, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=104.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 P1047', tradingClass='OZF')
Error 10197, reqId 2702: No market data during competing live session, contract: Contract(secType='FOP', conId=842944558, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=105.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 C1052', tradingClass='OZF')
Error 10197, reqId 2304: No market data during competing live session, contract: Contract(secType='FOP', conId=885310378, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=109.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 P1097', tradingClass='WF1')
Error 10197, reqId 2362: No market data during competing live session, contract: Contract(secType='FOP', conId=885751674, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=108.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 P1082', tradingClass='HF1')
Error 10197, reqId 2144: No market data during competing live session, contract: Contract(secType='FOP', conId=881985860, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=109.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 C1097', tradingClass='VF1')
Error 10197, reqId 1931: No market data during competing live session, contract: Contract(secType='FOP', conId=882727573, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=104.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 C1045', tradingClass='WF4')
Error 10197, reqId 2436: No market data during competing live session, contract: Contract(secType='FOP', conId=881572262, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=110.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 P1107', tradingClass='ZF1')
Error 10197, reqId 2181: No market data during competing live session, contract: Contract(secType='FOP', conId=885029016, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=103.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 C1030', tradingClass='GF1')
Error 10197, reqId 2740: No market data during competing live session, contract: Contract(secType='FOP', conId=842944656, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=106.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 P1067', tradingClass='OZF')
Error 10197, reqId 2124: No market data during competing live session, contract: Contract(secType='FOP', conId=881986177, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=104.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 C1047', tradingClass='VF1')
Error 10197, reqId 2409: No market data during competing live session, contract: Contract(secType='FOP', conId=881572502, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=104.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 P1040', tradingClass='ZF1')
Error 10197, reqId 2251: No market data during competing live session, contract: Contract(secType='FOP', conId=885310364, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=104.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 C1045', tradingClass='WF1')
Error 10197, reqId 2682: No market data during competing live session, contract: Contract(secType='FOP', conId=869662877, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=108.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 P1082', tradingClass='OZF')
Error 10197, reqId 2056: No market data during competing live session, contract: Contract(secType='FOP', conId=879598736, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=103.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 C1037', tradingClass='ZF5')
Error 10197, reqId 2552: No market data during competing live session, contract: Contract(secType='FOP', conId=884607277, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=107.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 P1077', tradingClass='ZF2')
Error 10197, reqId 2204: No market data during competing live session, contract: Contract(secType='FOP', conId=885029088, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=108.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 C1087', tradingClass='GF1')
Error 10197, reqId 2185: No market data during competing live session, contract: Contract(secType='FOP', conId=885029125, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=104.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 C1040', tradingClass='GF1')
Error 10197, reqId 2350: No market data during competing live session, contract: Contract(secType='FOP', conId=885751614, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=105.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 P1052', tradingClass='HF1')
Error 10197, reqId 2380: No market data during competing live session, contract: Contract(secType='FOP', conId=881572427, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=104.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 C1047', tradingClass='ZF1')
Error 10197, reqId 2323: No market data during competing live session, contract: Contract(secType='FOP', conId=885751679, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=106.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 C1065', tradingClass='HF1')
Error 10197, reqId 2171: No market data during competing live session, contract: Contract(secType='FOP', conId=881986032, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=108.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 P1085', tradingClass='VF1')
Error 10197, reqId 2418: No market data during competing live session, contract: Contract(secType='FOP', conId=881572493, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=106.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 P1062', tradingClass='ZF1')
Error 10197, reqId 2832: No market data during competing live session, contract: Contract(secType='FOP', conId=870223056, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=105.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 C1057', tradingClass='OZF')
Error 10197, reqId 1942: No market data during competing live session, contract: Contract(secType='FOP', conId=882727537, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=107.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 C1072', tradingClass='WF4')
Error 10197, reqId 2071: No market data during competing live session, contract: Contract(secType='FOP', conId=879598655, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=107.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 C1075', tradingClass='ZF5')
Error 10197, reqId 2293: No market data during competing live session, contract: Contract(secType='FOP', conId=885310273, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=107.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 P1070', tradingClass='WF1')
Error 10197, reqId 1936: No market data during competing live session, contract: Contract(secType='FOP', conId=882727553, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=105.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 C1057', tradingClass='WF4')
Error 10197, reqId 2278: No market data during competing live session, contract: Contract(secType='FOP', conId=885310327, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=103.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 P1032', tradingClass='WF1')
Error 10197, reqId 2064: No market data during competing live session, contract: Contract(secType='FOP', conId=879598855, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=105.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 C1057', tradingClass='ZF5')
Error 10197, reqId 2421: No market data during competing live session, contract: Contract(secType='FOP', conId=881572522, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=107.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 P1070', tradingClass='ZF1')
Error 10197, reqId 2038: No market data during competing live session, contract: Contract(secType='FOP', conId=883636027, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=107.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 P1072', tradingClass='HF4')
Error 10197, reqId 2089: No market data during competing live session, contract: Contract(secType='FOP', conId=879598658, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=104.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 P1040', tradingClass='ZF5')
Error 10197, reqId 1920: No market data during competing live session, contract: Contract(secType='FOP', conId=882370247, symbol='ZF', lastTradeDateOrContractMonth='20260526', strike=107.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF4K6 P1077', tradingClass='GF4')
Error 10197, reqId 2189: No market data during competing live session, contract: Contract(secType='FOP', conId=885029165, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=105.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 C1050', tradingClass='GF1')
Error 10197, reqId 2496: No market data during competing live session, contract: Contract(secType='FOP', conId=884728287, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=109.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 P1097', tradingClass='VF2')
Error 10197, reqId 2595: No market data during competing live session, contract: Contract(secType='FOP', conId=849162916, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=110.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 C1105', tradingClass='OZF')
Error 10197, reqId 2880: No market data during competing live session, contract: Contract(secType='FOP', conId=870222832, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=109.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 P1097', tradingClass='OZF')
Error 10197, reqId 2512: No market data during competing live session, contract: Contract(secType='FOP', conId=884607162, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=105.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1057', tradingClass='ZF2')
Error 10197, reqId 1965: No market data during competing live session, contract: Contract(secType='FOP', conId=882727467, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=105.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 P1050', tradingClass='WF4')
Error 10197, reqId 2643: No market data during competing live session, contract: Contract(secType='FOP', conId=869663180, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=106.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 C1065', tradingClass='OZF')
Error 10197, reqId 2274: No market data during competing live session, contract: Contract(secType='FOP', conId=885310163, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=110.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 C1102', tradingClass='WF1')

[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session

Error 10197, reqId 2184: No market data during competing live session, contract: Contract(secType='FOP', conId=885029137, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=103.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 C1037', tradingClass='GF1')
Error 10197, reqId 2331: No market data during competing live session, contract: Contract(secType='FOP', conId=885751625, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=108.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 C1085', tradingClass='HF1')
Error 10197, reqId 2025: No market data during competing live session, contract: Contract(secType='FOP', conId=883636273, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=104.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 P1040', tradingClass='HF4')
Error 10197, reqId 2252: No market data during competing live session, contract: Contract(secType='FOP', conId=885310126, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=104.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 C1047', tradingClass='WF1')
Error 10197, reqId 2473: No market data during competing live session, contract: Contract(secType='FOP', conId=884728111, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=104.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 P1040', tradingClass='VF2')
Error 10197, reqId 2543: No market data during competing live session, contract: Contract(secType='FOP', conId=884607157, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=105.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 P1055', tradingClass='ZF2')
Error 10197, reqId 2075: No market data during competing live session, contract: Contract(secType='FOP', conId=879598570, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=108.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 C1085', tradingClass='ZF5')
Error 10197, reqId 1954: No market data during competing live session, contract: Contract(secType='FOP', conId=882727413, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=110.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 C1102', tradingClass='WF4')
Error 10197, reqId 2624: No market data during competing live session, contract: Contract(secType='FOP', conId=849162951, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=109.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 P1097', tradingClass='OZF')
Error 10197, reqId 2150: No market data during competing live session, contract: Contract(secType='FOP', conId=881985952, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=103.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 P1032', tradingClass='VF1')
Error 10197, reqId 2397: No market data during competing live session, contract: Contract(secType='FOP', conId=881572303, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=109.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 C1090', tradingClass='ZF1')
Error 10197, reqId 2622: No market data during competing live session, contract: Contract(secType='FOP', conId=849163218, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=109.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 P1092', tradingClass='OZF')
Error 10197, reqId 2156: No market data during competing live session, contract: Contract(secType='FOP', conId=881986060, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=104.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 P1047', tradingClass='VF1')
Error 10197, reqId 2388: No market data during competing live session, contract: Contract(secType='FOP', conId=881572362, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=106.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 C1067', tradingClass='ZF1')
Error 10197, reqId 2151: No market data during competing live session, contract: Contract(secType='FOP', conId=881986054, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=103.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 P1035', tradingClass='VF1')
Error 10197, reqId 1895: No market data during competing live session, contract: Contract(secType='FOP', conId=882369919, symbol='ZF', lastTradeDateOrContractMonth='20260526', strike=105.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF4K6 C1055', tradingClass='GF4')
Error 10197, reqId 2712: No market data during competing live session, contract: Contract(secType='FOP', conId=842944856, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=107.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 C1077', tradingClass='OZF')
Error 10197, reqId 2567: No market data during competing live session, contract: Contract(secType='FOP', conId=849163003, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=103.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 C1035', tradingClass='OZF')
Error 10197, reqId 2663: No market data during competing live session, contract: Contract(secType='FOP', conId=869663021, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=103.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 P1035', tradingClass='OZF')
Error 10197, reqId 2670: No market data during competing live session, contract: Contract(secType='FOP', conId=869663151, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=105.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 P1052', tradingClass='OZF')
Error 10197, reqId 2627: No market data during competing live session, contract: Contract(secType='FOP', conId=849162938, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=110.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 P1105', tradingClass='OZF')
Error 10197, reqId 2255: No market data during competing live session, contract: Contract(secType='FOP', conId=885310055, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=105.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 C1055', tradingClass='WF1')
Error 10197, reqId 2461: No market data during competing live session, contract: Contract(secType='FOP', conId=884728394, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=109.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1090', tradingClass='VF2')
Error 10197, reqId 2202: No market data during competing live session, contract: Contract(secType='FOP', conId=885029108, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=108.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 C1082', tradingClass='GF1')
Error 10197, reqId 2212: No market data during competing live session, contract: Contract(secType='FOP', conId=885028938, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=110.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 C1107', tradingClass='GF1')
Error 10197, reqId 1919: No market data during competing live session, contract: Contract(secType='FOP', conId=882370166, symbol='ZF', lastTradeDateOrContractMonth='20260526', strike=107.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF4K6 P1075', tradingClass='GF4')
Error 10197, reqId 2538: No market data during competing live session, contract: Contract(secType='FOP', conId=884607259, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=104.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 P1042', tradingClass='ZF2')
Error 10197, reqId 2576: No market data during competing live session, contract: Contract(secType='FOP', conId=849163266, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=105.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 C1057', tradingClass='OZF')
Error 10197, reqId 2443: No market data during competing live session, contract: Contract(secType='FOP', conId=884728257, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=104.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1045', tradingClass='VF2')
Error 10197, reqId 2466: No market data during competing live session, contract: Contract(secType='FOP', conId=884728222, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=110.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1102', tradingClass='VF2')
Error 10197, reqId 2152: No market data during competing live session, contract: Contract(secType='FOP', conId=881986197, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=103.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 P1037', tradingClass='VF1')
Error 10197, reqId 2732: No market data during competing live session, contract: Contract(secType='FOP', conId=842944947, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=104.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 P1047', tradingClass='OZF')
Error 10197, reqId 2327: No market data during competing live session, contract: Contract(secType='FOP', conId=885751542, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=107.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 C1075', tradingClass='HF1')
Error 10197, reqId 2742: No market data during competing live session, contract: Contract(secType='FOP', conId=842944890, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=107.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 P1072', tradingClass='OZF')
Error 10197, reqId 2247: No market data during competing live session, contract: Contract(secType='FOP', conId=885310083, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=103.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 C1035', tradingClass='WF1')
Error 10197, reqId 2407: No market data during competing live session, contract: Contract(secType='FOP', conId=881572228, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=103.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 P1035', tradingClass='ZF1')
Error 10197, reqId 2758: No market data during competing live session, contract: Contract(secType='FOP', conId=877321932, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=103.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 C1032', tradingClass='OZF')
Error 10197, reqId 2016: No market data during competing live session, contract: Contract(secType='FOP', conId=883636030, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=109.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 C1097', tradingClass='HF4')
Error 10197, reqId 2504: No market data during competing live session, contract: Contract(secType='FOP', conId=884607070, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=103.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1037', tradingClass='ZF2')
Error 10197, reqId 2321: No market data during competing live session, contract: Contract(secType='FOP', conId=885751645, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=106.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 C1060', tradingClass='HF1')
Error 10197, reqId 2555: No market data during competing live session, contract: Contract(secType='FOP', conId=884607271, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=108.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 P1085', tradingClass='ZF2')
Error 10197, reqId 2347: No market data during competing live session, contract: Contract(secType='FOP', conId=885751760, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=104.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 P1045', tradingClass='HF1')
Error 10197, reqId 1975: No market data during competing live session, contract: Contract(secType='FOP', conId=882727303, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=107.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 P1075', tradingClass='WF4')
Error 10197, reqId 1924: No market data during competing live session, contract: Contract(secType='FOP', conId=882370169, symbol='ZF', lastTradeDateOrContractMonth='20260526', strike=108.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF4K6 P1087', tradingClass='GF4')
Error 10197, reqId 2287: No market data during competing live session, contract: Contract(secType='FOP', conId=885310151, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=105.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 P1055', tradingClass='WF1')
Error 10197, reqId 2220: No market data during competing live session, contract: Contract(secType='FOP', conId=885028979, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=104.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 P1047', tradingClass='GF1')
Error 10197, reqId 2649: No market data during competing live session, contract: Contract(secType='FOP', conId=869663278, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=108.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 C1080', tradingClass='OZF')
Error 10197, reqId 2803: No market data during competing live session, contract: Contract(secType='FOP', conId=877322141, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=106.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 P1065', tradingClass='OZF')
Error 10197, reqId 2716: No market data during competing live session, contract: Contract(secType='FOP', conId=842944618, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=108.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 C1087', tradingClass='OZF')
Error 10197, reqId 2079: No market data during competing live session, contract: Contract(secType='FOP', conId=879598818, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=109.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 C1095', tradingClass='ZF5')
Error 10197, reqId 2837: No market data during competing live session, contract: Contract(secType='FOP', conId=870222837, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=107.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 C1070', tradingClass='OZF')
Error 10197, reqId 2271: No market data during competing live session, contract: Contract(secType='FOP', conId=885310033, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=109.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 C1095', tradingClass='WF1')
Error 10197, reqId 2265: No market data during competing live session, contract: Contract(secType='FOP', conId=885310191, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=108.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 C1080', tradingClass='WF1')
Error 10197, reqId 2349: No market data during competing live session, contract: Contract(secType='FOP', conId=885751799, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=105.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 P1050', tradingClass='HF1')
Error 10197, reqId 2479: No market data during competing live session, contract: Contract(secType='FOP', conId=884728311, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=105.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 P1055', tradingClass='VF2')
Error 10197, reqId 2117: No market data during competing live session, contract: Contract(secType='FOP', conId=881985962, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=103.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 C1030', tradingClass='VF1')
Error 10197, reqId 2775: No market data during competing live session, contract: Contract(secType='FOP', conId=877321738, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=107.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 C1075', tradingClass='OZF')
Error 10197, reqId 2218: No market data during competing live session, contract: Contract(secType='FOP', conId=885028852, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=104.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 P1042', tradingClass='GF1')
Error 10197, reqId 2211: No market data during competing live session, contract: Contract(secType='FOP', conId=885028813, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=110.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 C1105', tradingClass='GF1')
Error 10197, reqId 2085: No market data during competing live session, contract: Contract(secType='FOP', conId=879598560, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=103.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 P1030', tradingClass='ZF5')
Error 10197, reqId 2320: No market data during competing live session, contract: Contract(secType='FOP', conId=885751611, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=105.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 C1057', tradingClass='HF1')
Error 10197, reqId 2054: No market data during competing live session, contract: Contract(secType='FOP', conId=879598823, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=103.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 C1032', tradingClass='ZF5')
Error 10197, reqId 2656: No market data during competing live session, contract: Contract(secType='FOP', conId=869662891, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=109.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 C1097', tradingClass='OZF')
Error 10197, reqId 1911: No market data during competing live session, contract: Contract(secType='FOP', conId=882370182, symbol='ZF', lastTradeDateOrContractMonth='20260526', strike=105.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF4K6 P1055', tradingClass='GF4')
Error 10197, reqId 1989: No market data during competing live session, contract: Contract(secType='FOP', conId=883636382, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=103.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 C1030', tradingClass='HF4')
Error 10197, reqId 2057: No market data during competing live session, contract: Contract(secType='FOP', conId=879598541, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=104.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 C1040', tradingClass='ZF5')

[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session

Error 10197, reqId 2772: No market data during competing live session, contract: Contract(secType='FOP', conId=877321915, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=106.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 C1067', tradingClass='OZF')
Error 10197, reqId 2030: No market data during competing live session, contract: Contract(secType='FOP', conId=883636291, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=105.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 P1052', tradingClass='HF4')
Error 10197, reqId 2514: No market data during competing live session, contract: Contract(secType='FOP', conId=884607176, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=106.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1062', tradingClass='ZF2')
Error 10197, reqId 2198: No market data during competing live session, contract: Contract(secType='FOP', conId=885029160, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=107.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 C1072', tradingClass='GF1')
Error 10197, reqId 1921: No market data during competing live session, contract: Contract(secType='FOP', conId=882370089, symbol='ZF', lastTradeDateOrContractMonth='20260526', strike=108.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF4K6 P1080', tradingClass='GF4')
Error 10197, reqId 2846: No market data during competing live session, contract: Contract(secType='FOP', conId=870223110, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=109.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 C1092', tradingClass='OZF')
Error 10197, reqId 2507: No market data during competing live session, contract: Contract(secType='FOP', conId=884607312, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=104.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1045', tradingClass='ZF2')
Error 10197, reqId 2268: No market data during competing live session, contract: Contract(secType='FOP', conId=885310344, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=108.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 C1087', tradingClass='WF1')
Error 10197, reqId 1967: No market data during competing live session, contract: Contract(secType='FOP', conId=882727324, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=105.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 P1055', tradingClass='WF4')
Error 10197, reqId 2771: No market data during competing live session, contract: Contract(secType='FOP', conId=877321869, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=106.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 C1065', tradingClass='OZF')
Error 10197, reqId 2531: No market data during competing live session, contract: Contract(secType='FOP', conId=884607167, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=110.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1105', tradingClass='ZF2')
Error 10197, reqId 2449: No market data during competing live session, contract: Contract(secType='FOP', conId=884728466, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=106.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1060', tradingClass='VF2')
Error 10197, reqId 2652: No market data during competing live session, contract: Contract(secType='FOP', conId=869662931, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=108.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 C1087', tradingClass='OZF')
Error 10197, reqId 2509: No market data during competing live session, contract: Contract(secType='FOP', conId=884607094, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=105.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1050', tradingClass='ZF2')
Error 10197, reqId 2657: No market data during competing live session, contract: Contract(secType='FOP', conId=869663204, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=110.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 C1100', tradingClass='OZF')
Error 10197, reqId 2600: No market data during competing live session, contract: Contract(secType='FOP', conId=849162889, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=103.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 P1037', tradingClass='OZF')
Error 10197, reqId 2438: No market data during competing live session, contract: Contract(secType='FOP', conId=884728471, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=103.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1032', tradingClass='VF2')
Error 10197, reqId 2556: No market data during competing live session, contract: Contract(secType='FOP', conId=884607230, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=108.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 P1087', tradingClass='ZF2')
Error 10197, reqId 2399: No market data during competing live session, contract: Contract(secType='FOP', conId=881572293, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=109.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 C1095', tradingClass='ZF1')
Error 10197, reqId 2801: No market data during competing live session, contract: Contract(secType='FOP', conId=877321893, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=106.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 P1060', tradingClass='OZF')
Error 10197, reqId 2410: No market data during competing live session, contract: Contract(secType='FOP', conId=881572488, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=104.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 P1042', tradingClass='ZF1')
Error 10197, reqId 2859: No market data during competing live session, contract: Contract(secType='FOP', conId=870222861, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=104.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 P1045', tradingClass='OZF')
Error 10197, reqId 2667: No market data during competing live session, contract: Contract(secType='FOP', conId=869662824, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=104.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 P1045', tradingClass='OZF')
Error 10197, reqId 2112: No market data during competing live session, contract: Contract(secType='FOP', conId=879598547, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=109.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 P1097', tradingClass='ZF5')
Error 10197, reqId 2788: No market data during competing live session, contract: Contract(secType='FOP', conId=877321848, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=110.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 C1107', tradingClass='OZF')
Error 10197, reqId 2339: No market data during competing live session, contract: Contract(secType='FOP', conId=885751639, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=110.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 C1105', tradingClass='HF1')
Error 10197, reqId 1957: No market data during competing live session, contract: Contract(secType='FOP', conId=882727433, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=103.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 P1030', tradingClass='WF4')
Error 10197, reqId 2745: No market data during competing live session, contract: Contract(secType='FOP', conId=842944878, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=108.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 P1080', tradingClass='OZF')
Error 10197, reqId 2741: No market data during competing live session, contract: Contract(secType='FOP', conId=842944911, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=107.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 P1070', tradingClass='OZF')
Error 10197, reqId 2346: No market data during competing live session, contract: Contract(secType='FOP', conId=885751559, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=104.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 P1042', tradingClass='HF1')
Error 10197, reqId 2762: No market data during competing live session, contract: Contract(secType='FOP', conId=877322121, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=104.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 C1042', tradingClass='OZF')
Error 10197, reqId 2796: No market data during competing live session, contract: Contract(secType='FOP', conId=877322105, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=104.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 P1047', tradingClass='OZF')
Error 10197, reqId 2174: No market data during competing live session, contract: Contract(secType='FOP', conId=881985990, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=109.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 P1092', tradingClass='VF1')
Error 10197, reqId 2099: No market data during competing live session, contract: Contract(secType='FOP', conId=879598575, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=106.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 P1065', tradingClass='ZF5')
Error 10197, reqId 2318: No market data during competing live session, contract: Contract(secType='FOP', conId=885751560, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=105.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 C1052', tradingClass='HF1')
Error 10197, reqId 2034: No market data during competing live session, contract: Contract(secType='FOP', conId=883636306, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=106.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 P1062', tradingClass='HF4')
Error 10197, reqId 2573: No market data during competing live session, contract: Contract(secType='FOP', conId=849163065, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=105.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 C1050', tradingClass='OZF')
Error 10197, reqId 1985: No market data during competing live session, contract: Contract(secType='FOP', conId=882727596, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=110.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 P1100', tradingClass='WF4')
Error 10197, reqId 2823: No market data during competing live session, contract: Contract(secType='FOP', conId=870222935, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=103.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 C1035', tradingClass='OZF')
Error 10197, reqId 2250: No market data during competing live session, contract: Contract(secType='FOP', conId=885310061, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=104.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 C1042', tradingClass='WF1')
Error 10197, reqId 2236: No market data during competing live session, contract: Contract(secType='FOP', conId=885028828, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=108.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 P1087', tradingClass='GF1')
Error 10197, reqId 2833: No market data during competing live session, contract: Contract(secType='FOP', conId=870222657, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=106.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 C1060', tradingClass='OZF')
Error 10197, reqId 2316: No market data during competing live session, contract: Contract(secType='FOP', conId=885751468, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=104.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 C1047', tradingClass='HF1')
Error 10197, reqId 2458: No market data during competing live session, contract: Contract(secType='FOP', conId=884728146, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=108.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1082', tradingClass='VF2')
Error 10197, reqId 1940: No market data during competing live session, contract: Contract(secType='FOP', conId=882727487, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=106.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 C1067', tradingClass='WF4')
Error 10197, reqId 2307: No market data during competing live session, contract: Contract(secType='FOP', conId=885310157, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=110.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 P1105', tradingClass='WF1')
Error 10197, reqId 2442: No market data during competing live session, contract: Contract(secType='FOP', conId=884728451, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=104.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1042', tradingClass='VF2')
Error 10197, reqId 2731: No market data during competing live session, contract: Contract(secType='FOP', conId=842944810, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=104.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 P1045', tradingClass='OZF')
Error 10197, reqId 2052: No market data during competing live session, contract: Contract(secType='FOP', conId=883636336, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=110.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 P1107', tradingClass='HF4')
Error 10197, reqId 2371: No market data during competing live session, contract: Contract(secType='FOP', conId=885751652, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=110.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 P1105', tradingClass='HF1')
Error 10197, reqId 2364: No market data during competing live session, contract: Contract(secType='FOP', conId=885751779, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=108.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 P1087', tradingClass='HF1')
Error 10197, reqId 1902: No market data during competing live session, contract: Contract(secType='FOP', conId=882369940, symbol='ZF', lastTradeDateOrContractMonth='20260526', strike=107.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF4K6 C1072', tradingClass='GF4')
Error 10197, reqId 2774: No market data during competing live session, contract: Contract(secType='FOP', conId=877321823, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=107.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 C1072', tradingClass='OZF')
Error 10197, reqId 2678: No market data during competing live session, contract: Contract(secType='FOP', conId=869663214, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=107.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 P1072', tradingClass='OZF')
Error 10197, reqId 2489: No market data during competing live session, contract: Contract(secType='FOP', conId=884728157, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=108.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 P1080', tradingClass='VF2')
Error 10197, reqId 2109: No market data during competing live session, contract: Contract(secType='FOP', conId=879598640, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=109.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 P1090', tradingClass='ZF5')
Error 10197, reqId 1917: No market data during competing live session, contract: Contract(secType='FOP', conId=882370200, symbol='ZF', lastTradeDateOrContractMonth='20260526', strike=107.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF4K6 P1070', tradingClass='GF4')
Error 10197, reqId 2017: No market data during competing live session, contract: Contract(secType='FOP', conId=883636000, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=110.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 C1100', tradingClass='HF4')
Error 10197, reqId 2853: No market data during competing live session, contract: Contract(secType='FOP', conId=870222986, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=103.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 P1030', tradingClass='OZF')
Error 10197, reqId 2519: No market data during competing live session, contract: Contract(secType='FOP', conId=884607060, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=107.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1075', tradingClass='ZF2')
Error 10197, reqId 2277: No market data during competing live session, contract: Contract(secType='FOP', conId=885310092, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=103.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 P1030', tradingClass='WF1')
Error 10197, reqId 2013: No market data during competing live session, contract: Contract(secType='FOP', conId=883636020, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=109.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 C1090', tradingClass='HF4')
Error 10197, reqId 2767: No market data during competing live session, contract: Contract(secType='FOP', conId=877321691, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=105.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 C1055', tradingClass='OZF')
Error 10197, reqId 2303: No market data during competing live session, contract: Contract(secType='FOP', conId=885310208, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=109.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 P1095', tradingClass='WF1')
Error 10197, reqId 2720: No market data during competing live session, contract: Contract(secType='FOP', conId=842944793, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=109.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 C1097', tradingClass='OZF')
Error 10197, reqId 2709: No market data during competing live session, contract: Contract(secType='FOP', conId=842944986, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=107.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 C1070', tradingClass='OZF')

[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session

Error 10197, reqId 2014: No market data during competing live session, contract: Contract(secType='FOP', conId=883636130, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=109.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 C1092', tradingClass='HF4')
Error 10197, reqId 2055: No market data during competing live session, contract: Contract(secType='FOP', conId=879598645, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=103.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 C1035', tradingClass='ZF5')
Error 10197, reqId 2048: No market data during competing live session, contract: Contract(secType='FOP', conId=883636136, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=109.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 P1097', tradingClass='HF4')
Error 10197, reqId 2147: No market data during competing live session, contract: Contract(secType='FOP', conId=881986084, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=110.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 C1105', tradingClass='VF1')
Error 10197, reqId 2789: No market data during competing live session, contract: Contract(secType='FOP', conId=877322063, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=103.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 P1030', tradingClass='OZF')
Error 10197, reqId 2266: No market data during competing live session, contract: Contract(secType='FOP', conId=885310152, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=108.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 C1082', tradingClass='WF1')
Error 10197, reqId 2241: No market data during competing live session, contract: Contract(secType='FOP', conId=885028919, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=110.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 P1100', tradingClass='GF1')
Error 10197, reqId 2557: No market data during competing live session, contract: Contract(secType='FOP', conId=884607402, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=109.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 P1090', tradingClass='ZF2')
Error 10197, reqId 2295: No market data during competing live session, contract: Contract(secType='FOP', conId=885310223, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=107.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 P1075', tradingClass='WF1')
Error 10197, reqId 2692: No market data during competing live session, contract: Contract(secType='FOP', conId=869662829, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=110.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 P1107', tradingClass='OZF')
Error 10197, reqId 2460: No market data during competing live session, contract: Contract(secType='FOP', conId=884728272, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=108.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1087', tradingClass='VF2')
Error 10197, reqId 2019: No market data during competing live session, contract: Contract(secType='FOP', conId=883636256, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=110.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 C1105', tradingClass='HF4')
Error 10197, reqId 2369: No market data during competing live session, contract: Contract(secType='FOP', conId=885751459, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=110.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 P1100', tradingClass='HF1')
Error 10197, reqId 1970: No market data during competing live session, contract: Contract(secType='FOP', conId=882727396, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=106.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 P1062', tradingClass='WF4')
Error 10197, reqId 2601: No market data during competing live session, contract: Contract(secType='FOP', conId=849162898, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=104.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 P1040', tradingClass='OZF')
Error 10197, reqId 2122: No market data during competing live session, contract: Contract(secType='FOP', conId=881986106, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=104.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 C1042', tradingClass='VF1')
Error 10197, reqId 2340: No market data during competing live session, contract: Contract(secType='FOP', conId=885751565, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=110.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 C1107', tradingClass='HF1')
Error 10197, reqId 1932: No market data during competing live session, contract: Contract(secType='FOP', conId=882727358, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=104.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 C1047', tradingClass='WF4')
Error 10197, reqId 1907: No market data during competing live session, contract: Contract(secType='FOP', conId=882370152, symbol='ZF', lastTradeDateOrContractMonth='20260526', strike=108.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF4K6 C1085', tradingClass='GF4')
Error 10197, reqId 1929: No market data during competing live session, contract: Contract(secType='FOP', conId=882727661, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=104.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 C1040', tradingClass='WF4')
Error 10197, reqId 2706: No market data during competing live session, contract: Contract(secType='FOP', conId=842944744, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=106.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 C1062', tradingClass='OZF')
Error 10197, reqId 2760: No market data during competing live session, contract: Contract(secType='FOP', conId=877322010, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=103.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 C1037', tradingClass='OZF')
Error 10197, reqId 2563: No market data during competing live session, contract: Contract(secType='FOP', conId=884607407, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=110.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 P1105', tradingClass='ZF2')
Error 10197, reqId 2228: No market data during competing live session, contract: Contract(secType='FOP', conId=885028982, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=106.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 P1067', tradingClass='GF1')
Error 10197, reqId 2047: No market data during competing live session, contract: Contract(secType='FOP', conId=883636150, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=109.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 P1095', tradingClass='HF4')
Error 10197, reqId 2351: No market data during competing live session, contract: Contract(secType='FOP', conId=885751685, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=105.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 P1055', tradingClass='HF1')
Error 10197, reqId 2217: No market data during competing live session, contract: Contract(secType='FOP', conId=885029171, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=104.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 P1040', tradingClass='GF1')
Error 10197, reqId 2203: No market data during competing live session, contract: Contract(secType='FOP', conId=885028789, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=108.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 C1085', tradingClass='GF1')
Error 10197, reqId 2415: No market data during competing live session, contract: Contract(secType='FOP', conId=881572188, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=105.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 P1055', tradingClass='ZF1')
Error 10197, reqId 2338: No market data during competing live session, contract: Contract(secType='FOP', conId=885751455, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=110.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 C1102', tradingClass='HF1')
Error 10197, reqId 2367: No market data during competing live session, contract: Contract(secType='FOP', conId=885751649, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=109.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 P1095', tradingClass='HF1')
Error 10197, reqId 2448: No market data during competing live session, contract: Contract(secType='FOP', conId=884728358, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=105.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1057', tradingClass='VF2')
Error 10197, reqId 1986: No market data during competing live session, contract: Contract(secType='FOP', conId=882727293, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=110.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 P1102', tradingClass='WF4')
Error 10197, reqId 2511: No market data during competing live session, contract: Contract(secType='FOP', conId=884607357, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=105.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1055', tradingClass='ZF2')
Error 10197, reqId 2757: No market data during competing live session, contract: Contract(secType='FOP', conId=877321983, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=103.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 C1030', tradingClass='OZF')
Error 10197, reqId 2348: No market data during competing live session, contract: Contract(secType='FOP', conId=885751545, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=104.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 P1047', tradingClass='HF1')
Error 10197, reqId 2665: No market data during competing live session, contract: Contract(secType='FOP', conId=869663003, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=104.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 P1040', tradingClass='OZF')
Error 10197, reqId 2341: No market data during competing live session, contract: Contract(secType='FOP', conId=885751628, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=103.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 P1030', tradingClass='HF1')
Error 10197, reqId 1950: No market data during competing live session, contract: Contract(secType='FOP', conId=882727345, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=109.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 C1092', tradingClass='WF4')
Error 10197, reqId 2738: No market data during competing live session, contract: Contract(secType='FOP', conId=842944916, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=106.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 P1062', tradingClass='OZF')
Error 10197, reqId 1987: No market data during competing live session, contract: Contract(secType='FOP', conId=882727477, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=110.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 P1105', tradingClass='WF4')
Error 10197, reqId 2814: No market data during competing live session, contract: Contract(secType='FOP', conId=877322039, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=109.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 P1092', tradingClass='OZF')
Error 10197, reqId 2850: No market data during competing live session, contract: Contract(secType='FOP', conId=870223030, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=110.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 C1102', tradingClass='OZF')
Error 10197, reqId 1956: No market data during competing live session, contract: Contract(secType='FOP', conId=882727453, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=110.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 C1107', tradingClass='WF4')
Error 10197, reqId 1926: No market data during competing live session, contract: Contract(secType='FOP', conId=882727366, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=103.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 C1032', tradingClass='WF4')
Error 10197, reqId 2139: No market data during competing live session, contract: Contract(secType='FOP', conId=881985906, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=108.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 C1085', tradingClass='VF1')
Error 10197, reqId 2114: No market data during competing live session, contract: Contract(secType='FOP', conId=879598770, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=110.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 P1102', tradingClass='ZF5')
Error 10197, reqId 2494: No market data during competing live session, contract: Contract(secType='FOP', conId=884728140, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=109.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 P1092', tradingClass='VF2')
Error 10197, reqId 2302: No market data during competing live session, contract: Contract(secType='FOP', conId=885310086, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=109.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 P1092', tradingClass='WF1')
Error 10197, reqId 2795: No market data during competing live session, contract: Contract(secType='FOP', conId=877322015, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=104.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 P1045', tradingClass='OZF')
Error 10197, reqId 2328: No market data during competing live session, contract: Contract(secType='FOP', conId=885751554, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=107.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 C1077', tradingClass='HF1')
Error 10197, reqId 2173: No market data during competing live session, contract: Contract(secType='FOP', conId=881986154, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=109.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 P1090', tradingClass='VF1')
Error 10197, reqId 2452: No market data during competing live session, contract: Contract(secType='FOP', conId=884728249, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=106.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1067', tradingClass='VF2')
Error 10197, reqId 2469: No market data during competing live session, contract: Contract(secType='FOP', conId=884728435, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=103.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 P1030', tradingClass='VF2')
Error 10197, reqId 2696: No market data during competing live session, contract: Contract(secType='FOP', conId=842944709, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=103.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 C1037', tradingClass='OZF')
Error 10197, reqId 1990: No market data during competing live session, contract: Contract(secType='FOP', conId=883635996, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=103.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 C1032', tradingClass='HF4')
Error 10197, reqId 2430: No market data during competing live session, contract: Contract(secType='FOP', conId=881572212, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=109.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 P1092', tradingClass='ZF1')
Error 10197, reqId 1974: No market data during competing live session, contract: Contract(secType='FOP', conId=882727646, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=107.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 P1072', tradingClass='WF4')
Error 10197, reqId 2433: No market data during competing live session, contract: Contract(secType='FOP', conId=881572397, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=110.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 P1100', tradingClass='ZF1')
Error 10197, reqId 2439: No market data during competing live session, contract: Contract(secType='FOP', conId=884728370, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=103.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1035', tradingClass='VF2')
Error 10197, reqId 2158: No market data during competing live session, contract: Contract(secType='FOP', conId=881985972, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=105.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 P1052', tradingClass='VF1')
Error 10197, reqId 2100: No market data during competing live session, contract: Contract(secType='FOP', conId=879598493, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=106.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 P1067', tradingClass='ZF5')
Error 10197, reqId 2777: No market data during competing live session, contract: Contract(secType='FOP', conId=877322145, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=108.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 C1080', tradingClass='OZF')
Error 10197, reqId 2001: No market data during competing live session, contract: Contract(secType='FOP', conId=883636186, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=106.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 C1060', tradingClass='HF4')
Error 10197, reqId 2493: No market data during competing live session, contract: Contract(secType='FOP', conId=884728151, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=109.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 P1090', tradingClass='VF2')
Error 10197, reqId 2746: No market data during competing live session, contract: Contract(secType='FOP', conId=842944885, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=108.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 P1082', tradingClass='OZF')

[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session

Error 10197, reqId 2213: No market data during competing live session, contract: Contract(secType='FOP', conId=885029147, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=103.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 P1030', tradingClass='GF1')
Error 10197, reqId 2508: No market data during competing live session, contract: Contract(secType='FOP', conId=884607317, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=104.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1047', tradingClass='ZF2')
Error 10197, reqId 2800: No market data during competing live session, contract: Contract(secType='FOP', conId=877322088, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=105.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 P1057', tradingClass='OZF')
Error 10197, reqId 2165: No market data during competing live session, contract: Contract(secType='FOP', conId=881985911, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=107.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 P1070', tradingClass='VF1')
Error 10197, reqId 2756: No market data during competing live session, contract: Contract(secType='FOP', conId=842944690, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=110.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 P1107', tradingClass='OZF')
Error 10197, reqId 2462: No market data during competing live session, contract: Contract(secType='FOP', conId=884728131, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=109.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1092', tradingClass='VF2')
Error 10197, reqId 2703: No market data during competing live session, contract: Contract(secType='FOP', conId=842945021, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=105.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 C1055', tradingClass='OZF')
Error 10197, reqId 2162: No market data during competing live session, contract: Contract(secType='FOP', conId=881985927, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=106.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 P1062', tradingClass='VF1')
Error 10197, reqId 2104: No market data during competing live session, contract: Contract(secType='FOP', conId=879598587, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=107.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 P1077', tradingClass='ZF5')
Error 10197, reqId 2024: No market data during competing live session, contract: Contract(secType='FOP', conId=883636276, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=103.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 P1037', tradingClass='HF4')
Error 10197, reqId 1916: No market data during competing live session, contract: Contract(secType='FOP', conId=882370059, symbol='ZF', lastTradeDateOrContractMonth='20260526', strike=106.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF4K6 P1067', tradingClass='GF4')
Error 10197, reqId 2058: No market data during competing live session, contract: Contract(secType='FOP', conId=879598650, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=104.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 C1042', tradingClass='ZF5')
Error 10197, reqId 2787: No market data during competing live session, contract: Contract(secType='FOP', conId=877322118, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=110.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 C1105', tradingClass='OZF')
Error 10197, reqId 2386: No market data during competing live session, contract: Contract(secType='FOP', conId=881572487, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=106.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 C1062', tradingClass='ZF1')
Error 10197, reqId 2141: No market data during competing live session, contract: Contract(secType='FOP', conId=881985877, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=109.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 C1090', tradingClass='VF1')
Error 10197, reqId 2806: No market data during competing live session, contract: Contract(secType='FOP', conId=877321745, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=107.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 P1072', tradingClass='OZF')
Error 10197, reqId 2033: No market data during competing live session, contract: Contract(secType='FOP', conId=883636232, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=106.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 P1060', tradingClass='HF4')
Error 10197, reqId 2108: No market data during competing live session, contract: Contract(secType='FOP', conId=879598764, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=108.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 P1087', tradingClass='ZF5')
Error 10197, reqId 2630: No market data during competing live session, contract: Contract(secType='FOP', conId=869663030, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=103.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 C1032', tradingClass='OZF')
Error 10197, reqId 2111: No market data during competing live session, contract: Contract(secType='FOP', conId=879598580, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=109.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 P1095', tradingClass='ZF5')
Error 10197, reqId 2568: No market data during competing live session, contract: Contract(secType='FOP', conId=849162904, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=103.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 C1037', tradingClass='OZF')
Error 10197, reqId 2620: No market data during competing live session, contract: Contract(secType='FOP', conId=849163164, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=108.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 P1087', tradingClass='OZF')
Error 10197, reqId 2296: No market data during competing live session, contract: Contract(secType='FOP', conId=885310166, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=107.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 P1077', tradingClass='WF1')
Error 10197, reqId 2525: No market data during competing live session, contract: Contract(secType='FOP', conId=884607085, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=109.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1090', tradingClass='ZF2')
Error 10197, reqId 2427: No market data during competing live session, contract: Contract(secType='FOP', conId=881572318, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=108.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 P1085', tradingClass='ZF1')
Error 10197, reqId 2723: No market data during competing live session, contract: Contract(secType='FOP', conId=842944764, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=110.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 C1105', tradingClass='OZF')
Error 10197, reqId 2705: No market data during competing live session, contract: Contract(secType='FOP', conId=842944875, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=106.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 C1060', tradingClass='OZF')
Error 10197, reqId 2802: No market data during competing live session, contract: Contract(secType='FOP', conId=877321733, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=106.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 P1062', tradingClass='OZF')
Error 10197, reqId 2096: No market data during competing live session, contract: Contract(secType='FOP', conId=879598758, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=105.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 P1057', tradingClass='ZF5')
Error 10197, reqId 2136: No market data during competing live session, contract: Contract(secType='FOP', conId=881985979, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=107.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 C1077', tradingClass='VF1')
Error 10197, reqId 2093: No market data during competing live session, contract: Contract(secType='FOP', conId=879598824, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=105.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 P1050', tradingClass='ZF5')
Error 10197, reqId 2750: No market data during competing live session, contract: Contract(secType='FOP', conId=842944953, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=109.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 P1092', tradingClass='OZF')
Error 10197, reqId 1984: No market data during competing live session, contract: Contract(secType='FOP', conId=882727448, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=109.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 P1097', tradingClass='WF4')
Error 10197, reqId 2357: No market data during competing live session, contract: Contract(secType='FOP', conId=885751734, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=107.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 P1070', tradingClass='HF1')
Error 10197, reqId 2200: No market data during competing live session, contract: Contract(secType='FOP', conId=885028905, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=107.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 C1077', tradingClass='GF1')
Error 10197, reqId 2654: No market data during competing live session, contract: Contract(secType='FOP', conId=869663081, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=109.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 C1092', tradingClass='OZF')
Error 10197, reqId 2577: No market data during competing live session, contract: Contract(secType='FOP', conId=849163028, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=106.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 C1060', tradingClass='OZF')
Error 10197, reqId 2191: No market data during competing live session, contract: Contract(secType='FOP', conId=885029140, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=105.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 C1055', tradingClass='GF1')
Error 10197, reqId 2408: No market data during competing live session, contract: Contract(secType='FOP', conId=881572238, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=103.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 P1037', tradingClass='ZF1')
Error 10197, reqId 2561: No market data during competing live session, contract: Contract(secType='FOP', conId=884607351, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=110.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 P1100', tradingClass='ZF2')
Error 10197, reqId 2084: No market data during competing live session, contract: Contract(secType='FOP', conId=879598693, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=110.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 C1107', tradingClass='ZF5')
Error 10197, reqId 2004: No market data during competing live session, contract: Contract(secType='FOP', conId=883636141, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=106.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 C1067', tradingClass='HF4')
Error 10197, reqId 1964: No market data during competing live session, contract: Contract(secType='FOP', conId=882727550, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=104.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 P1047', tradingClass='WF4')
Error 10197, reqId 2547: No market data during competing live session, contract: Contract(secType='FOP', conId=884607242, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=106.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 P1065', tradingClass='ZF2')
Error 10197, reqId 2816: No market data during competing live session, contract: Contract(secType='FOP', conId=877321953, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=109.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 P1097', tradingClass='OZF')
Error 10197, reqId 2536: No market data during competing live session, contract: Contract(secType='FOP', conId=884607436, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=103.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 P1037', tradingClass='ZF2')
Error 10197, reqId 2301: No market data during competing live session, contract: Contract(secType='FOP', conId=885309993, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=109.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 P1090', tradingClass='WF1')
Error 10197, reqId 2329: No market data during competing live session, contract: Contract(secType='FOP', conId=885751695, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=108.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 C1080', tradingClass='HF1')
Error 10197, reqId 1999: No market data during competing live session, contract: Contract(secType='FOP', conId=883636334, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=105.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 C1055', tradingClass='HF4')
Error 10197, reqId 2215: No market data during competing live session, contract: Contract(secType='FOP', conId=885028819, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=103.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 P1035', tradingClass='GF1')
Error 10197, reqId 2506: No market data during competing live session, contract: Contract(secType='FOP', conId=884607433, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=104.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1042', tradingClass='ZF2')
Error 10197, reqId 2395: No market data during competing live session, contract: Contract(secType='FOP', conId=881572391, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=108.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 C1085', tradingClass='ZF1')
Error 10197, reqId 2717: No market data during competing live session, contract: Contract(secType='FOP', conId=842944761, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=109.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 C1090', tradingClass='OZF')
Error 10197, reqId 2232: No market data during competing live session, contract: Contract(secType='FOP', conId=885029103, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=107.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 P1077', tradingClass='GF1')
Error 10197, reqId 2344: No market data during competing live session, contract: Contract(secType='FOP', conId=885751800, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=103.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 P1037', tradingClass='HF1')
Error 10197, reqId 2526: No market data during competing live session, contract: Contract(secType='FOP', conId=884607283, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=109.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1092', tradingClass='ZF2')
Error 10197, reqId 2444: No market data during competing live session, contract: Contract(secType='FOP', conId=884728231, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=104.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1047', tradingClass='VF2')
Error 10197, reqId 2510: No market data during competing live session, contract: Contract(secType='FOP', conId=884607200, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=105.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1052', tradingClass='ZF2')
Error 10197, reqId 2390: No market data during competing live session, contract: Contract(secType='FOP', conId=881572539, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=107.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 C1072', tradingClass='ZF1')
Error 10197, reqId 2523: No market data during competing live session, contract: Contract(secType='FOP', conId=884607430, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=108.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1085', tradingClass='ZF2')
Error 10197, reqId 2882: No market data during competing live session, contract: Contract(secType='FOP', conId=870222847, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=110.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 P1102', tradingClass='OZF')
Error 10197, reqId 2279: No market data during competing live session, contract: Contract(secType='FOP', conId=885310286, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=103.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 P1035', tradingClass='WF1')
Error 10197, reqId 2831: No market data during competing live session, contract: Contract(secType='FOP', conId=870222652, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=105.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 C1055', tradingClass='OZF')
Error 10197, reqId 2275: No market data during competing live session, contract: Contract(secType='FOP', conId=885310213, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=110.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 C1105', tradingClass='WF1')
Error 10197, reqId 2406: No market data during competing live session, contract: Contract(secType='FOP', conId=881572274, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=103.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 P1032', tradingClass='ZF1')
Error 10197, reqId 2332: No market data during competing live session, contract: Contract(secType='FOP', conId=885751589, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=108.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 C1087', tradingClass='HF1')

[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session

Error 10197, reqId 2576: No market data during competing live session, contract: Contract(secType='FOP', conId=849163266, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=105.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 C1057', tradingClass='OZF')
Error 10197, reqId 2726: No market data during competing live session, contract: Contract(secType='FOP', conId=842944961, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=103.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 P1032', tradingClass='OZF')
Error 10197, reqId 1930: No market data during competing live session, contract: Contract(secType='FOP', conId=882727427, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=104.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 C1042', tradingClass='WF4')
Error 10197, reqId 2159: No market data during competing live session, contract: Contract(secType='FOP', conId=881986137, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=105.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 P1055', tradingClass='VF1')
Error 10197, reqId 2450: No market data during competing live session, contract: Contract(secType='FOP', conId=884728134, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=106.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1062', tradingClass='VF2')
Error 10197, reqId 2152: No market data during competing live session, contract: Contract(secType='FOP', conId=881986197, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=103.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 P1037', tradingClass='VF1')
Error 10197, reqId 2443: No market data during competing live session, contract: Contract(secType='FOP', conId=884728257, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=104.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1045', tradingClass='VF2')
Error 10197, reqId 2615: No market data during competing live session, contract: Contract(secType='FOP', conId=849163229, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=107.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 P1075', tradingClass='OZF')
Error 10197, reqId 2669: No market data during competing live session, contract: Contract(secType='FOP', conId=869663304, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=105.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 P1050', tradingClass='OZF')
Error 10197, reqId 2763: No market data during competing live session, contract: Contract(secType='FOP', conId=877321888, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=104.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 C1045', tradingClass='OZF')
Error 10197, reqId 2131: No market data during competing live session, contract: Contract(secType='FOP', conId=881985857, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=106.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 C1065', tradingClass='VF1')
Error 10197, reqId 2856: No market data during competing live session, contract: Contract(secType='FOP', conId=870223113, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=103.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 P1037', tradingClass='OZF')
Error 10197, reqId 2466: No market data during competing live session, contract: Contract(secType='FOP', conId=884728222, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=110.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1102', tradingClass='VF2')
Error 10197, reqId 2387: No market data during competing live session, contract: Contract(secType='FOP', conId=881572568, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=106.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 C1065', tradingClass='ZF1')
Error 10197, reqId 2447: No market data during competing live session, contract: Contract(secType='FOP', conId=884728381, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=105.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1055', tradingClass='VF2')
Error 10197, reqId 2695: No market data during competing live session, contract: Contract(secType='FOP', conId=842944635, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=103.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 C1035', tradingClass='OZF')
Error 10197, reqId 2428: No market data during competing live session, contract: Contract(secType='FOP', conId=881572562, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=108.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 P1087', tradingClass='ZF1')
Error 10197, reqId 2597: No market data during competing live session, contract: Contract(secType='FOP', conId=849162933, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=103.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 P1030', tradingClass='OZF')
Error 10197, reqId 2343: No market data during competing live session, contract: Contract(secType='FOP', conId=885751775, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=103.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 P1035', tradingClass='HF1')
Error 10197, reqId 2645: No market data during competing live session, contract: Contract(secType='FOP', conId=869663075, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=107.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 C1070', tradingClass='OZF')
Error 10197, reqId 2719: No market data during competing live session, contract: Contract(secType='FOP', conId=842944696, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=109.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 C1095', tradingClass='OZF')
Error 10197, reqId 2029: No market data during competing live session, contract: Contract(secType='FOP', conId=883636065, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=105.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 P1050', tradingClass='HF4')
Error 10197, reqId 2521: No market data during competing live session, contract: Contract(secType='FOP', conId=884607334, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=108.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1080', tradingClass='ZF2')
Error 10197, reqId 2851: No market data during competing live session, contract: Contract(secType='FOP', conId=870222694, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=110.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 C1105', tradingClass='OZF')
Error 10197, reqId 2554: No market data during competing live session, contract: Contract(secType='FOP', conId=884607442, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=108.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 P1082', tradingClass='ZF2')
Error 10197, reqId 2373: No market data during competing live session, contract: Contract(secType='FOP', conId=881572553, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=103.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 C1030', tradingClass='ZF1')
Error 10197, reqId 2642: No market data during competing live session, contract: Contract(secType='FOP', conId=869662881, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=106.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 C1062', tradingClass='OZF')
Error 10197, reqId 1906: No market data during competing live session, contract: Contract(secType='FOP', conId=882369925, symbol='ZF', lastTradeDateOrContractMonth='20260526', strike=108.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF4K6 C1082', tradingClass='GF4')
Error 10197, reqId 2564: No market data during competing live session, contract: Contract(secType='FOP', conId=884607262, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=110.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 P1107', tradingClass='ZF2')
Error 10197, reqId 2361: No market data during competing live session, contract: Contract(secType='FOP', conId=885751821, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=108.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 P1080', tradingClass='HF1')
Error 10197, reqId 2602: No market data during competing live session, contract: Contract(secType='FOP', conId=849163155, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=104.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 P1042', tradingClass='OZF')
Error 10197, reqId 2545: No market data during competing live session, contract: Contract(secType='FOP', conId=884607247, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=106.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 P1060', tradingClass='ZF2')
Error 10197, reqId 2183: No market data during competing live session, contract: Contract(secType='FOP', conId=885028859, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=103.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 C1035', tradingClass='GF1')
Error 10197, reqId 2239: No market data during competing live session, contract: Contract(secType='FOP', conId=885029120, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=109.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 P1095', tradingClass='GF1')
Error 10197, reqId 2142: No market data during competing live session, contract: Contract(secType='FOP', conId=881986071, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=109.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 C1092', tradingClass='VF1')
Error 10197, reqId 2637: No market data during competing live session, contract: Contract(secType='FOP', conId=869663241, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=105.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 C1050', tradingClass='OZF')
Error 10197, reqId 2465: No market data during competing live session, contract: Contract(secType='FOP', conId=884728116, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=110.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1100', tradingClass='VF2')
Error 10197, reqId 1937: No market data during competing live session, contract: Contract(secType='FOP', conId=882727593, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=106.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 C1060', tradingClass='WF4')
Error 10197, reqId 2222: No market data during competing live session, contract: Contract(secType='FOP', conId=885028847, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=105.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 P1052', tradingClass='GF1')
Error 10197, reqId 2834: No market data during competing live session, contract: Contract(secType='FOP', conId=870222767, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=106.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 C1062', tradingClass='OZF')
Error 10197, reqId 2280: No market data during competing live session, contract: Contract(secType='FOP', conId=885310073, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=103.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 P1037', tradingClass='WF1')
Error 10197, reqId 2178: No market data during competing live session, contract: Contract(secType='FOP', conId=881986057, symbol='ZF', lastTradeDateOrContractMonth='20260601', strike=110.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF1M6 P1102', tradingClass='VF1')
Error 10197, reqId 2471: No market data during competing live session, contract: Contract(secType='FOP', conId=884728384, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=103.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 P1035', tradingClass='VF2')
Error 10197, reqId 2824: No market data during competing live session, contract: Contract(secType='FOP', conId=870222802, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=103.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 C1037', tradingClass='OZF')
Error 10197, reqId 2804: No market data during competing live session, contract: Contract(secType='FOP', conId=877321842, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=106.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 P1067', tradingClass='OZF')
Error 10197, reqId 2022: No market data during competing live session, contract: Contract(secType='FOP', conId=883636176, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=103.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 P1032', tradingClass='HF4')
Error 10197, reqId 2311: No market data during competing live session, contract: Contract(secType='FOP', conId=885751580, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=103.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 C1035', tradingClass='HF1')
Error 10197, reqId 2334: No market data during competing live session, contract: Contract(secType='FOP', conId=885751745, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=109.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 C1092', tradingClass='HF1')
Error 10197, reqId 2205: No market data during competing live session, contract: Contract(secType='FOP', conId=885029001, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=109.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 C1090', tradingClass='GF1')
Error 10197, reqId 2195: No market data during competing live session, contract: Contract(secType='FOP', conId=885028875, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=106.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 C1065', tradingClass='GF1')
Error 10197, reqId 2502: No market data during competing live session, contract: Contract(secType='FOP', conId=884607215, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=103.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 C1032', tradingClass='ZF2')
Error 10197, reqId 1976: No market data during competing live session, contract: Contract(secType='FOP', conId=882727287, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=107.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 P1077', tradingClass='WF4')
Error 10197, reqId 2470: No market data during competing live session, contract: Contract(secType='FOP', conId=884728300, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=103.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 P1032', tradingClass='VF2')
Error 10197, reqId 2590: No market data during competing live session, contract: Contract(secType='FOP', conId=849162957, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=109.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 C1092', tradingClass='OZF')
Error 10197, reqId 2404: No market data during competing live session, contract: Contract(secType='FOP', conId=881572550, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=110.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 C1107', tradingClass='ZF1')
Error 10197, reqId 2587: No market data during competing live session, contract: Contract(secType='FOP', conId=849163008, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=108.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 C1085', tradingClass='OZF')
Error 10197, reqId 2609: No market data during competing live session, contract: Contract(secType='FOP', conId=849163272, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=106.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 P1060', tradingClass='OZF')
Error 10197, reqId 2397: No market data during competing live session, contract: Contract(secType='FOP', conId=881572303, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=109.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 C1090', tradingClass='ZF1')
Error 10197, reqId 2487: No market data during competing live session, contract: Contract(secType='FOP', conId=884728113, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=107.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 P1075', tradingClass='VF2')
Error 10197, reqId 2248: No market data during competing live session, contract: Contract(secType='FOP', conId=885310103, symbol='ZF', lastTradeDateOrContractMonth='20260603', strike=103.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF1M6 C1037', tradingClass='WF1')
Error 10197, reqId 2079: No market data during competing live session, contract: Contract(secType='FOP', conId=879598818, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=109.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 C1095', tradingClass='ZF5')
Error 10197, reqId 2837: No market data during competing live session, contract: Contract(secType='FOP', conId=870222837, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=107.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 C1070', tradingClass='OZF')
Error 10197, reqId 2207: No market data during competing live session, contract: Contract(secType='FOP', conId=885029040, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=109.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 C1095', tradingClass='GF1')
Error 10197, reqId 2550: No market data during competing live session, contract: Contract(secType='FOP', conId=884607292, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=107.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 P1072', tradingClass='ZF2')
Error 10197, reqId 2194: No market data during competing live session, contract: Contract(secType='FOP', conId=885029177, symbol='ZF', lastTradeDateOrContractMonth='20260602', strike=106.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF1M6 C1062', tradingClass='GF1')
Error 10197, reqId 2391: No market data during competing live session, contract: Contract(secType='FOP', conId=881572222, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=107.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 C1075', tradingClass='ZF1')

[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session

Error 10197, reqId 2498: No market data during competing live session, contract: Contract(secType='FOP', conId=884728267, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=110.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 P1102', tradingClass='VF2')
Error 10197, reqId 2322: No market data during competing live session, contract: Contract(secType='FOP', conId=885751465, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=106.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 C1062', tradingClass='HF1')
Error 10197, reqId 1897: No market data during competing live session, contract: Contract(secType='FOP', conId=882370224, symbol='ZF', lastTradeDateOrContractMonth='20260526', strike=106.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF4K6 C1060', tradingClass='GF4')
Error 10197, reqId 2497: No market data during competing live session, contract: Contract(secType='FOP', conId=884728197, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=110.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 P1100', tradingClass='VF2')
Error 10197, reqId 2585: No market data during competing live session, contract: Contract(secType='FOP', conId=849163248, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=108.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 C1080', tradingClass='OZF')
Error 10197, reqId 1904: No market data during competing live session, contract: Contract(secType='FOP', conId=882370052, symbol='ZF', lastTradeDateOrContractMonth='20260526', strike=107.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF4K6 C1077', tradingClass='GF4')
Error 10197, reqId 2862: No market data during competing live session, contract: Contract(secType='FOP', conId=870222779, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=105.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 P1052', tradingClass='OZF')
Error 10197, reqId 1908: No market data during competing live session, contract: Contract(secType='FOP', conId=882370212, symbol='ZF', lastTradeDateOrContractMonth='20260526', strike=108.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF4K6 C1087', tradingClass='GF4')
Error 10197, reqId 1993: No market data during competing live session, contract: Contract(secType='FOP', conId=883636351, symbol='ZF', lastTradeDateOrContractMonth='20260528', strike=104.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF4K6 C1040', tradingClass='HF4')
Error 10197, reqId 2870: No market data during competing live session, contract: Contract(secType='FOP', conId=870222945, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=107.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 P1072', tradingClass='OZF')
Error 10197, reqId 2337: No market data during competing live session, contract: Contract(secType='FOP', conId=885751805, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=110.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 C1100', tradingClass='HF1')
Error 10197, reqId 2476: No market data during competing live session, contract: Contract(secType='FOP', conId=884728243, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=104.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 P1047', tradingClass='VF2')
Error 10197, reqId 2710: No market data during competing live session, contract: Contract(secType='FOP', conId=842944575, symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=107.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFU6 C1072', tradingClass='OZF')
Error 10197, reqId 2781: No market data during competing live session, contract: Contract(secType='FOP', conId=877321830, symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=109.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFV6 C1090', tradingClass='OZF')
Error 10197, reqId 1913: No market data during competing live session, contract: Contract(secType='FOP', conId=882369977, symbol='ZF', lastTradeDateOrContractMonth='20260526', strike=106.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='GF4K6 P1060', tradingClass='GF4')
Error 10197, reqId 2871: No market data during competing live session, contract: Contract(secType='FOP', conId=870222727, symbol='ZF', lastTradeDateOrContractMonth='20261120', strike=107.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFZ6 P1075', tradingClass='OZF')
Error 10197, reqId 2688: No market data during competing live session, contract: Contract(secType='FOP', conId=869662940, symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=109.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFQ6 P1097', tradingClass='OZF')
Error 10197, reqId 2405: No market data during competing live session, contract: Contract(secType='FOP', conId=881572437, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=103.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 P1030', tradingClass='ZF1')
Error 10197, reqId 2425: No market data during competing live session, contract: Contract(secType='FOP', conId=881572529, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=108.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 P1080', tradingClass='ZF1')
Error 10197, reqId 2446: No market data during competing live session, contract: Contract(secType='FOP', conId=884728176, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=105.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1052', tradingClass='VF2')
Error 10197, reqId 2063: No market data during competing live session, contract: Contract(secType='FOP', conId=879598755, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=105.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 C1055', tradingClass='ZF5')
Error 10197, reqId 2445: No market data during competing live session, contract: Contract(secType='FOP', conId=884728161, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=105.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1050', tradingClass='VF2')
Error 10197, reqId 2087: No market data during competing live session, contract: Contract(secType='FOP', conId=879598751, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=103.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 P1035', tradingClass='ZF5')
Error 10197, reqId 2624: No market data during competing live session, contract: Contract(secType='FOP', conId=849162951, symbol='ZF', lastTradeDateOrContractMonth='20260626', strike=109.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='OZFN6 P1097', tradingClass='OZF')
Error 10197, reqId 2359: No market data during competing live session, contract: Contract(secType='FOP', conId=885751440, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=107.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 P1075', tradingClass='HF1')
Error 10197, reqId 2464: No market data during competing live session, contract: Contract(secType='FOP', conId=884728260, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=109.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 C1097', tradingClass='VF2')
Error 10197, reqId 2558: No market data during competing live session, contract: Contract(secType='FOP', conId=884607220, symbol='ZF', lastTradeDateOrContractMonth='20260612', strike=109.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF2M6 P1092', tradingClass='ZF2')
Error 10197, reqId 2499: No market data during competing live session, contract: Contract(secType='FOP', conId=884728101, symbol='ZF', lastTradeDateOrContractMonth='20260608', strike=110.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='VF2M6 P1105', tradingClass='VF2')
Error 10197, reqId 1946: No market data during competing live session, contract: Contract(secType='FOP', conId=882727510, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=108.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 C1082', tradingClass='WF4')
Error 10197, reqId 2417: No market data during competing live session, contract: Contract(secType='FOP', conId=881572308, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=106.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 P1060', tradingClass='ZF1')
Error 10197, reqId 2325: No market data during competing live session, contract: Contract(secType='FOP', conId=885751710, symbol='ZF', lastTradeDateOrContractMonth='20260604', strike=107.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='HF1M6 C1070', tradingClass='HF1')
Error 10197, reqId 2411: No market data during competing live session, contract: Contract(secType='FOP', conId=881572508, symbol='ZF', lastTradeDateOrContractMonth='20260605', strike=104.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF1M6 P1045', tradingClass='ZF1')
Error 10197, reqId 1949: No market data during competing live session, contract: Contract(secType='FOP', conId=882727547, symbol='ZF', lastTradeDateOrContractMonth='20260527', strike=109.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='WF4K6 C1090', tradingClass='WF4')
Error 10197, reqId 2065: No market data during competing live session, contract: Contract(secType='FOP', conId=879598838, symbol='ZF', lastTradeDateOrContractMonth='20260529', strike=106.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', localSymbol='ZF5K6 C1060', tradingClass='ZF5')

[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session
[IB error] 10197: No market data during competing live session

Error 1100, reqId -1: Connectivity between IBKR and Trader Workstation has been lost.
Peer closed connection.

## 3. Get current future price

Use this cell to fetch the current price of a specified Treasury futures contract.

In [6]:
price_info = get_future_price(
    ib,
    ROOT,
    FUTURE_MONTHS[0],
    market_data_type=MARKET_DATA_TYPE,
)

print("contract:", price_info["localSymbol"], "conId:", price_info["conId"])
print("price:", price_info["price"], "source:", price_info["priceSource"])
pd.Series({k: v for k, v in price_info.items() if k not in ["contract", "ticker"]})

contract: ZFM6 conId: 818615223
price: 107.0859375 source: marketPrice

root                    ZF
month               202606
exchange              CBOT
conId            818615223
localSymbol           ZFM6
price           107.085938
priceSource    marketPrice
marketPrice     107.085938
mid             107.082031
last            107.085938
close            106.78125
bid             107.078125
ask             107.085938
dtype: object

## 3. 可选：自动发现后续底层期货月份

如果你不确定应该填哪些月份，先跑这个单元看 IB 返回了哪些 FUT 合约月份。

In [7]:
# 可选：如果 FUTURE_MONTHS 不确定，打开下面两行。
discovered = discover_future_months(ib, ROOT, min_month="202606", max_count=10)
discovered

['202606', '202609', '202612']

## 4. 枚举并缓存全量期权链

这里会对每一个底层期货月份分别调用 `reqSecDefOptParams(root, 'CBOT', 'FUT', underlying.conId)`，再按返回的 `tradingClass / expirations / strikes` 构造 FOP 合约。分批 `qualifyContracts` 后会保存 conId，后续刷新行情可以直接从 CSV 加载，不必每次重新 qualify。

In [8]:
universe = build_treasury_fop_universe(
    ib,
    root=ROOT,
    future_months=FUTURE_MONTHS,
    exchange="CBOT",
    fop_exchange="CBOT",
    qualify_batch_size=400,
)

save_universe(universe, UNIVERSE_CSV)
print("valid FOP contracts:", len(universe.contracts))
print("saved:", UNIVERSE_CSV)
display(universe.chain_summary)
display(universe.metadata.head(20))

underlying ZF202606: conId=818615223, localSymbol=ZFM6
  candidates from option chains: 0
underlying ZF202609: conId=842590380, localSymbol=ZFU6
  candidates from option chains: 1592
underlying ZF202612: conId=869928209, localSymbol=ZFZ6
  candidates from option chains: 280

Unknown contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=88.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Unknown contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=88.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Unknown contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=88.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Unknown contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=88.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Unknown contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=116.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Unknown contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=116.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Unknown contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=116.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Unknown contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=116.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Unknown contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=117.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Unknown contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=117.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Unknown contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=117.25, right='C', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Unknown contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=117.25, right='P', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Unknown contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=117.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Unknown contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260724', strike=117.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Unknown contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=88.5, right='C', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Unknown contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=88.5, right='P', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Unknown contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=88.75, right='C', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Unknown contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260821', strike=88.75, right='P', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')

Unknown contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=116.0, right='C', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')
Unknown contract: FuturesOption(symbol='ZF', lastTradeDateOrContractMonth='20260925', strike=116.0, right='P', multiplier='1000', exchange='CBOT', currency='USD', tradingClass='OZF')

qualified 1872/1872; valid 1852
valid FOP contracts: 1852
saved: ZF_FOP_Universe_202606_202609_202612.csv

    underlyingConId underlyingLocalSymbol underlyingMonth exchange tradingClass multiplier  expirationCount  strikeCount  candidateCount firstExpiration lastExpiration  minStrike  maxStrike
0         842590380                  ZFU6          202609     CBOT          VF1       1000                1           53             106        20260601       20260601     100.50     113.50
1         842590380                  ZFU6          202609     CBOT          GF1       1000                1           50             100        20260602       20260602     100.50     112.75
2         842590380                  ZFU6          202609     CBOT          WF1       1000                1           49              98        20260603       20260603     100.75     112.75
3         842590380                  ZFU6          202609     CBOT          VF2       1000                1           50             100        20260608       20260608     100.50     112.75
4         842590380                  ZFU6          202609     CBOT          HF1       1000                1           49              98        20260604       20260604     100.75     112.75
5         842590380                  ZFU6          202609     CBOT          GF4       1000                1           52             104        20260526       20260526     100.50     113.25
6         842590380                  ZFU6          202609     CBOT          WF4       1000                1           52             104        20260527       20260527     100.50     113.25
7         842590380                  ZFU6          202609     CBOT          ZF1       1000                1           54             108        20260605       20260605     100.50     113.75
8         842590380                  ZFU6          202609     CBOT          HF4       1000                1           52             104        20260528       20260528     100.50     113.25
9         842590380                  ZFU6          202609     CBOT          ZF2       1000                1           50             100        20260612       20260612     100.50     112.75
10        842590380                  ZFU6          202609     CBOT          ZF5       1000                1           54             108        20260529       20260529     100.50     113.75
11        842590380                  ZFU6          202609     CBOT          OZF       1000                3           77             462        20260626       20260821      88.50     117.50
12        869928209                  ZFZ6          202612     CBOT          OZF       1000                2           70             280        20260925       20261120      98.75     116.00

    underlyingConId underlyingLocalSymbol underlyingMonth chainExchange chainTradingClass chainMultiplier      conId secType symbol  localSymbol tradingClass lastTradeDateOrContractMonth  strike right multiplier exchange currency
0         842590380                  ZFU6          202609          CBOT               GF4            1000  884726993     FOP     ZF  GF4K6 C1005          GF4                     20260526  100.50     C       1000     CBOT      USD
1         842590380                  ZFU6          202609          CBOT               GF4            1000  884600076     FOP     ZF  GF4K6 C1007          GF4                     20260526  100.75     C       1000     CBOT      USD
2         842590380                  ZFU6          202609          CBOT               GF4            1000  884600082     FOP     ZF  GF4K6 C1010          GF4                     20260526  101.00     C       1000     CBOT      USD
3         842590380                  ZFU6          202609          CBOT               GF4            1000  882369874     FOP     ZF  GF4K6 C1012          GF4                     20260526  101.25     C       1000     CBOT      USD
4         842590380                  ZFU6          202609          CBOT               GF4            1000  882369988     FOP     ZF  GF4K6 C1015          GF4                     20260526  101.50     C       1000     CBOT      USD
5         842590380                  ZFU6          202609          CBOT               GF4            1000  882369892     FOP     ZF  GF4K6 C1017          GF4                     20260526  101.75     C       1000     CBOT      USD
6         842590380                  ZFU6          202609          CBOT               GF4            1000  882369885     FOP     ZF  GF4K6 C1020          GF4                     20260526  102.00     C       1000     CBOT      USD
7         842590380                  ZFU6          202609          CBOT               GF4            1000  882370185     FOP     ZF  GF4K6 C1022          GF4                     20260526  102.25     C       1000     CBOT      USD
8         842590380                  ZFU6          202609          CBOT               GF4            1000  882370234     FOP     ZF  GF4K6 C1025          GF4                     20260526  102.50     C       1000     CBOT      USD
9         842590380                  ZFU6          202609          CBOT               GF4            1000  882370079     FOP     ZF  GF4K6 C1027          GF4                     20260526  102.75     C       1000     CBOT      USD
10        842590380                  ZFU6          202609          CBOT               GF4            1000  882369960     FOP     ZF  GF4K6 C1030          GF4                     20260526  103.00     C       1000     CBOT      USD
11        842590380                  ZFU6          202609          CBOT               GF4            1000  882369914     FOP     ZF  GF4K6 C1032          GF4                     20260526  103.25     C       1000     CBOT      USD
12        842590380                  ZFU6          202609          CBOT               GF4            1000  882369959     FOP     ZF  GF4K6 C1035          GF4                     20260526  103.50     C       1000     CBOT      USD
13        842590380                  ZFU6          202609          CBOT               GF4            1000  882369868     FOP     ZF  GF4K6 C1037          GF4                     20260526  103.75     C       1000     CBOT      USD
14        842590380                  ZFU6          202609          CBOT               GF4            1000  882370028     FOP     ZF  GF4K6 C1040          GF4                     20260526  104.00     C       1000     CBOT      USD
15        842590380                  ZFU6          202609          CBOT               GF4            1000  882370122     FOP     ZF  GF4K6 C1042          GF4                     20260526  104.25     C       1000     CBOT      USD
16        842590380                  ZFU6          202609          CBOT               GF4            1000  882370045     FOP     ZF  GF4K6 C1045          GF4                     20260526  104.50     C       1000     CBOT      USD
17        842590380                  ZFU6          202609          CBOT               GF4            1000  882370163     FOP     ZF  GF4K6 C1047          GF4                     20260526  104.75     C       1000     CBOT      USD
18        842590380                  ZFU6          202609          CBOT               GF4            1000  882369902     FOP     ZF  GF4K6 C1050          GF4                     20260526  105.00     C       1000     CBOT      USD
19        842590380                  ZFU6          202609          CBOT               GF4            1000  882370062     FOP     ZF  GF4K6 C1052          GF4                     20260526  105.25     C       1000     CBOT      USD

## 5. 从缓存加载 universe

调试 market data 时建议从这里开始反复跑，减少 IB contract details 请求。

In [9]:
contracts, universe_df = load_universe(UNIVERSE_CSV)
universe_df["expiration"] = universe_df["lastTradeDateOrContractMonth"].astype(str)

summary = universe_df.groupby("underlyingMonth", dropna=False).agg(
    contracts=("conId", "count"),
    expirations=("expiration", "nunique"),
    firstExpiration=("expiration", "min"),
    lastExpiration=("expiration", "max"),
    minStrike=("strike", "min"),
    maxStrike=("strike", "max"),
)

print("loaded contracts:", len(contracts))
display(summary)
display(universe_df)

loaded contracts: 1852

                 contracts  expirations firstExpiration lastExpiration  minStrike  maxStrike
underlyingMonth
202609                1574           14        20260526       20260821      88.50      117.5
202612                 278            2        20260925       20261120      98.75      116.0

,underlyingConId,underlyingLocalSymbol,underlyingMonth,chainExchange,chainTradingClass,chainMultiplier,conId,secType,symbol,localSymbol,tradingClass,lastTradeDateOrContractMonth,strike,right,multiplier,exchange,currency,expiration
0,842590380,ZFU6,202609,CBOT,GF4,1000,884726993,FOP,ZF,GF4K6 C1005,GF4,20260526,100.50,C,1000,CBOT,USD,20260526
1,842590380,ZFU6,202609,CBOT,GF4,1000,884600076,FOP,ZF,GF4K6 C1007,GF4,20260526,100.75,C,1000,CBOT,USD,20260526
2,842590380,ZFU6,202609,CBOT,GF4,1000,884600082,FOP,ZF,GF4K6 C1010,GF4,20260526,101.00,C,1000,CBOT,USD,20260526
3,842590380,ZFU6,202609,CBOT,GF4,1000,882369874,FOP,ZF,GF4K6 C1012,GF4,20260526,101.25,C,1000,CBOT,USD,20260526
4,842590380,ZFU6,202609,CBOT,GF4,1000,882369988,FOP,ZF,GF4K6 C1015,GF4,20260526,101.50,C,1000,CBOT,USD,20260526
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1847,869928209,ZFZ6,202612,CBOT,OZF,1000,870222700,FOP,ZF,OZFZ6 P1150,OZF,20261120,115.00,P,1000,CBOT,USD,20261120
1848,869928209,ZFZ6,202612,CBOT,OZF,1000,870222757,FOP,ZF,OZFZ6 P1152,OZF,20261120,115.25,P,1000,CBOT,USD,20261120
1849,869928209,ZFZ6,202612,CBOT,OZF,1000,870222895,FOP,ZF,OZFZ6 P1155,OZF,20261120,115.50,P,1000,CBOT,USD,20261120
1850,869928209,ZFZ6,202612,CBOT,OZF,1000,870223010,FOP,ZF,OZFZ6 P1157,OZF,20261120,115.75,P,1000,CBOT,USD,20261120
1851,869928209,ZFZ6,202612,CBOT,OZF,1000,873497297,FOP,ZF,OZFZ6 P1160,OZF,20261120,116.00,P,1000,CBOT,USD,20261120

## 6. 过滤需要监控的合约

规则：0DTE 合约只保留距离当前期货价格 2 点以内的 strike；非 0DTE 合约保留 5 点以内。不同底层月份会分别使用对应期货合约的价格。

In [10]:
future_prices = get_future_prices_for_months(
    ib,
    ROOT,
    FUTURE_MONTHS,
    market_data_type=MARKET_DATA_TYPE,
)
spot_by_month = dict(zip(future_prices["month"].astype(str), future_prices["price"].astype(float)))

filtered_contracts, filtered_universe_df = filter_contracts_by_moneyness(
    contracts,
    universe_df,
    spot_by_underlying_month=spot_by_month,
    dte0_width=2.0,
    non_dte0_width=4.0,
)

print("original contracts:", len(contracts))
print("filtered contracts:", len(filtered_contracts))
display(future_prices)
display(
    filtered_universe_df.groupby(["underlyingMonth", "expiration", "dte0"], dropna=False)
    .agg(contracts=("conId", "count"), minStrike=("strike", "min"), maxStrike=("strike", "max"))
    .head(30)
)

original contracts: 1852
filtered contracts: 992

  root   month exchange      conId localSymbol       price  priceSource  marketPrice         mid        last       close         bid         ask
0   ZF  202606     CBOT  818615223        ZFM6  107.085938  marketPrice   107.085938  107.082031  107.085938  106.781250  107.078125  107.085938
1   ZF  202609     CBOT  842590380        ZFU6  106.984375  marketPrice   106.984375  106.980469  106.984375  106.664062  106.976562  106.984375
2   ZF  202612     CBOT  869928209        ZFZ6  106.976562  marketPrice   106.976562  106.894531  106.976562  106.640625  106.796875  106.992188

                                  contracts  minStrike  maxStrike
underlyingMonth expiration dte0
202609          20260526   True          32      105.0     108.75
                20260527   False         64      103.0     110.75
                20260528   False         64      103.0     110.75
                20260529   False         64      103.0     110.75
                20260601   False         64      103.0     110.75
                20260602   False         64      103.0     110.75
                20260603   False         64      103.0     110.75
                20260604   False         64      103.0     110.75
                20260605   False         64      103.0     110.75
                20260608   False         64      103.0     110.75
                20260612   False         64      103.0     110.75
                20260626   False         64      103.0     110.75
                20260724   False         64      103.0     110.75
                20260821   False         64      103.0     110.75
202612          20260925   False         64      103.0     110.75
                20261120   False         64      103.0     110.75

## 6. 小样本测试报价 / Greeks

先用 80 个合约确认权限、字段和到达速度。`genericTickList='100,101,106'` 会请求期权成交量、OI、IV/Greeks。

In [ ]:
# 不要用 contracts[:80] 做样本：排序最前面通常全是当日到期合约，IB 很容易返回 Model is not valid。
# 这里改为：优先从过滤后的 universe 中选非当日到期、ATM 附近、最近几个到期日。
today = pd.Timestamp.now(tz="Asia/Shanghai").strftime("%Y%m%d")
front_future = qualify_future(ib, ROOT, FUTURE_MONTHS[0])
fallback_spot = float(pd.to_numeric(universe_df["strike"], errors="coerce").median())
spot = get_reference_price(ib, front_future, fallback=fallback_spot)

sample_source_contracts = filtered_contracts if "filtered_contracts" in globals() else contracts
sample_source_df = filtered_universe_df if "filtered_universe_df" in globals() else universe_df

sample_contracts, sample_meta = select_atm_contracts(
    sample_source_contracts,
    sample_source_df,
    spot=spot,
    expiration_after=today,
    underlying_month=FUTURE_MONTHS[0],
    max_expirations=3,
    strikes_each_side=5,
)

print("today:", today, "spot:", spot, "sample size:", len(sample_contracts))
display(sample_meta[["underlyingMonth", "localSymbol", "expiration", "right", "strike", "conId"]].head(30))

sample_streamer = FOPMarketDataStreamer(ib, request_interval=0.025)
sample_streamer.subscribe(sample_contracts)
sample_stats = sample_streamer.wait_until_stable(min_seconds=5, max_seconds=20, stable_seconds=3)
sample_df = sample_streamer.snapshot()
sample_streamer.cancel()
sample_features = prepare_snapshot_features(sample_df, include_chinese_columns=True)

display(sample_stats)
display(summarize_snapshot(sample_df))
display(sample_features.head(20))

## 7. 全量并发订阅：最快刷新方式

这一步会保持所有 market data line 打开。之后每次 `streamer.snapshot()` 都只是读取内存中已经被 IB event loop 更新的 Ticker，速度最快。

如果这里报 market data line 上限，改用下一节的分批模式，或把 `active_contracts = contracts[:300]` 改小。

In [11]:
active_contracts = filtered_contracts if "filtered_contracts" in globals() else contracts
print("subscribing contracts:", len(active_contracts))

streamer = FOPMarketDataStreamer(ib, request_interval=0.01)
streamer.subscribe(active_contracts)
stats = streamer.wait_until_stable(max_seconds=20, stable_seconds=2)

df = streamer.snapshot()
df_features = prepare_snapshot_features(df, include_chinese_columns=True)
df.to_csv(SNAPSHOT_CSV, index=False, encoding="utf-8-sig")
FEATURES_CSV = SNAPSHOT_CSV.with_name(SNAPSHOT_CSV.stem + "_features_cn.csv")
df_features.to_csv(FEATURES_CSV, index=False, encoding="utf-8-sig")

display(stats)
display(summarize_snapshot(df))
display(df_features.head(20))
print("raw saved:", SNAPSHOT_CSV)
print("features saved:", FEATURES_CSV)

subscribing contracts: 992
sent 992/992 market data requests in 7.6s
ready quote=992/992, greeks=957/992, oi=893/992, volume=0/992, elapsed=18.9s

StreamStats(requested=992, quote_ready=992, greek_ready=957, oi_ready=893, volume_ready=0, elapsed_seconds=18.875)

contracts                  992
with_quote                 992
with_model_greeks          957
with_primary_delta         957
with_open_interest         893
with_volume                992
expirations                 16
min_expiration        20260526
max_expiration        20261120
dtype: object

,快照时间_北京时间,距离到期天数,快照时间_UTC,到期日,行权价,看涨看跌,买价,卖价,买卖中间价,最新成交价,昨收价,买量,卖量,未平仓量,IB期权隐含波动率tick,模型隐含波动率,Delta,Gamma,Theta,Vega,模型期权价,模型标的价
0,2026-05-26 14:56:11,0,2026-05-26 06:56:11.348822+0000,20260526,105.00,C,1.968750,1.984375,1.976562,NaN,1.664062,1.0,1.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-05-26 14:56:11,0,2026-05-26 06:56:11.348822+0000,20260526,105.25,C,1.718750,1.734375,1.726562,NaN,1.414062,1.0,1.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-05-26 14:56:11,0,2026-05-26 06:56:11.348822+0000,20260526,105.50,C,1.468750,1.484375,1.476562,NaN,1.164062,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-05-26 14:56:11,0,2026-05-26 06:56:11.348822+0000,20260526,105.75,C,1.218750,1.234375,1.226562,NaN,0.914062,1.0,1.0,NaN,0.084539,0.105256,9.985622e-01,1.144594e-02,-1.551028e-04,2.918950e-04,1.226718e+00,106.976562
4,2026-05-26 14:56:11,0,2026-05-26 06:56:11.348822+0000,20260526,106.00,C,0.968750,0.984375,0.976562,NaN,0.671875,26.0,36.0,NaN,0.066520,0.093895,9.960245e-01,3.175578e-02,-4.436633e-04,6.785561e-04,9.770062e-01,106.976562
5,2026-05-26 14:56:11,0,2026-05-26 06:56:11.348822+0000,20260526,106.25,C,0.718750,0.734375,0.726562,NaN,0.437500,36.0,36.0,417.0,0.050530,0.080869,9.887261e-01,9.211757e-02,-1.235987e-03,1.555297e-03,7.277985e-01,106.976562
6,2026-05-26 14:56:11,0,2026-05-26 06:56:11.348822+0000,20260526,106.50,C,0.468750,0.484375,0.476562,0.570312,0.242188,61.0,1.0,904.0,0.033078,0.066814,9.651419e-01,2.916339e-01,-3.655082e-03,3.939905e-03,4.802176e-01,106.976562
7,2026-05-26 14:56:11,0,2026-05-26 06:56:11.348822+0000,20260526,106.75,C,0.234375,0.250000,0.242188,NaN,0.109375,26.0,1.0,5448.0,0.053483,0.055441,8.493612e-01,1.066557e+00,-1.723692e-02,1.025360e-02,2.437994e-01,106.976562
8,2026-05-26 14:56:11,0,2026-05-26 06:56:11.348822+0000,20260526,107.00,C,0.062500,0.078125,0.070312,0.078125,0.039062,33989.0,15359.0,20231.0,0.051225,0.051905,4.551209e-01,1.928165e+00,-7.124346e-02,1.580375e-02,7.124346e-02,106.976562
9,2026-05-26 14:56:11,0,2026-05-26 06:56:11.348822+0000,20260526,107.25,C,0.007812,0.015625,0.011719,NaN,0.007812,23226.0,160289.0,3361.0,0.055888,0.056933,1.126527e-01,8.508107e-01,-1.236316e-02,8.603107e-03,1.236316e-02,106.976562
10,2026-05-26 14:56:11,0,2026-05-26 06:56:11.348822+0000,20260526,107.50,C,NaN,0.007812,NaN,NaN,0.007812,0.0,2899.0,635.0,NaN,0.061951,1.667002e-02,1.682958e-01,-1.484249e-03,2.262257e-03,1.484249e-03,106.976562
11,2026-05-26 14:56:11,0,2026-05-26 06:56:11.348822+0000,20260526,107.75,C,NaN,0.007812,NaN,NaN,0.000000,0.0,159942.0,18.0,NaN,0.063883,1.087047e-03,1.428799e-02,-7.757511e-05,2.950339e-04,7.757511e-05,106.976562
12,2026-05-26 14:56:11,0,2026-05-26 06:56:11.348822+0000,20260526,108.00,C,NaN,0.007812,NaN,NaN,0.000000,0.0,317211.0,0.0,NaN,0.065220,3.409775e-05,5.478666e-04,-2.037240e-06,1.902934e-05,2.037240e-06,106.976562
13,2026-05-26 14:56:11,0,2026-05-26 06:56:11.348822+0000,20260526,108.25,C,NaN,0.007812,NaN,NaN,0.000000,0.0,353956.0,0.0,NaN,0.067375,7.091647e-07,1.305406e-05,-3.746550e-08,9.706607e-07,3.746550e-08,106.976562
14,2026-05-26 14:56:11,0,2026-05-26 06:56:11.348822+0000,20260526,108.50,C,NaN,0.007812,NaN,NaN,0.000000,0.0,360629.0,0.0,NaN,0.070603,1.325850e-08,2.655065e-07,-6.488726e-10,4.571587e-08,6.488726e-10,106.976562
15,2026-05-26 14:56:11,0,2026-05-26 06:56:11.348822+0000,20260526,108.75,C,NaN,0.007812,NaN,NaN,0.000000,0.0,360866.0,0.0,NaN,0.074876,5.098321e-10,1.041081e-08,-2.456923e-11,2.413025e-09,2.456923e-11,106.976562
16,2026-05-26 14:56:11,0,2026-05-26 06:56:11.348822+0000,20260526,105.00,P,NaN,0.007812,NaN,NaN,0.000000,0.0,355037.0,68.0,NaN,0.141810,-1.698737e-04,1.145577e-03,-2.402021e-05,4.275992e-05,2.402021e-05,106.976562
17,2026-05-26 14:56:11,0,2026-05-26 06:56:11.348822+0000,20260526,105.25,P,NaN,0.007812,NaN,NaN,0.000000,0.0,373188.0,69.0,NaN,0.128715,-2.744812e-04,1.986160e-03,-3.605334e-05,7.072123e-05,3.605334e-05,106.976562
18,2026-05-26 14:56:11,0,2026-05-26 06:56:11.348822+0000,20260526,105.50,P,NaN,0.007812,NaN,NaN,0.000000,0.0,376499.0,70.0,NaN,0.116557,-5.690329e-04,4.317869e-03,-7.087677e-05,1.345010e-04,7.087677e-05,106.976562
19,2026-05-26 14:56:11,0,2026-05-26 06:56:11.348822+0000,20260526,105.75,P,NaN,0.007812,NaN,NaN,0.000000,0.0,375687.0,916.0,NaN,0.105256,-1.460513e-03,1.134260e-02,-1.761822e-04,2.959342e-04,1.761822e-04,106.976562

raw saved: ZF_FOP_Snapshot.csv
features saved: ZF_FOP_Snapshot_features_cn.csv

## 8. 快速刷新快照

保持上一节 `streamer` 不 cancel，然后反复运行这个单元即可刷新整条链的最新报价和 Greeks。

In [13]:
# ib.sleep(2)
df_refresh = streamer.snapshot()
df_refresh_features = prepare_snapshot_features(df_refresh, include_chinese_columns=True)
df_refresh.to_csv(SNAPSHOT_CSV, index=False, encoding="utf-8-sig")
FEATURES_CSV = SNAPSHOT_CSV.with_name(SNAPSHOT_CSV.stem + "_features_cn.csv")
df_refresh_features.to_csv(FEATURES_CSV, index=False, encoding="utf-8-sig")

display(summarize_snapshot(df_refresh))
display(df_refresh_features.head(20))
print("features saved:", FEATURES_CSV)

contracts                  992
with_quote                 992
with_model_greeks          992
with_primary_delta         992
with_open_interest         893
with_volume                992
expirations                 16
min_expiration        20260526
max_expiration        20261120
dtype: object

,快照时间_北京时间,距离到期天数,快照时间_UTC,到期日,行权价,看涨看跌,买价,卖价,买卖中间价,最新成交价,昨收价,买量,卖量,未平仓量,IB期权隐含波动率tick,模型隐含波动率,Delta,Gamma,Theta,Vega,模型期权价,模型标的价
0,2026-05-26 14:57:09,0,2026-05-26 06:57:09.344818+0000,20260526,105.00,C,1.968750,1.984375,1.976562,NaN,1.664062,1.0,1.0,9.0,NaN,0.141192,9.998961e-01,1.170873e-03,-6.232187e-06,3.277581e-05,1.976569e+00,106.976562
1,2026-05-26 14:57:09,0,2026-05-26 06:57:09.344818+0000,20260526,105.25,C,1.718750,1.734375,1.726562,NaN,1.414062,1.0,1.0,16.0,NaN,0.128177,9.997832e-01,2.011759e-03,-1.684266e-05,5.832362e-05,1.726579e+00,106.976562
2,2026-05-26 14:57:09,0,2026-05-26 06:57:09.344818+0000,20260526,105.50,C,1.468750,1.484375,1.476562,NaN,1.164062,1.0,1.0,NaN,NaN,0.116086,9.994898e-01,4.269791e-03,-4.818338e-05,1.199880e-04,1.476611e+00,106.976562
3,2026-05-26 14:57:09,0,2026-05-26 06:57:09.344818+0000,20260526,105.75,C,1.218750,1.234375,1.226562,NaN,0.914062,1.0,1.0,NaN,0.084539,0.104849,9.986384e-01,1.096570e-02,-1.447391e-04,2.831922e-04,1.226707e+00,106.976562
4,2026-05-26 14:57:09,0,2026-05-26 06:57:09.344818+0000,20260526,106.00,C,0.968750,0.984375,0.976562,NaN,0.671875,1.0,36.0,NaN,0.066520,0.093577,9.961320e-01,3.109827e-02,-4.286247e-04,6.509451e-04,9.769911e-01,106.976562
5,2026-05-26 14:57:09,0,2026-05-26 06:57:09.344818+0000,20260526,106.25,C,0.718750,0.734375,0.726562,NaN,0.437500,26.0,36.0,417.0,0.050530,0.080739,9.888712e-01,9.127895e-02,-1.215567e-03,1.542532e-03,7.277781e-01,106.976562
6,2026-05-26 14:57:09,0,2026-05-26 06:57:09.344818+0000,20260526,106.50,C,0.468750,0.484375,0.476562,0.570312,0.242188,61.0,36.0,904.0,0.033078,0.066988,9.648271e-01,2.931221e-01,-3.701551e-03,3.955032e-03,4.802641e-01,106.976562
7,2026-05-26 14:57:09,0,2026-05-26 06:57:09.344818+0000,20260526,106.75,C,0.234375,0.250000,0.242188,NaN,0.109375,26.0,1.0,5448.0,0.053483,0.055767,8.482073e-01,1.066868e+00,-1.748504e-02,1.030131e-02,2.440475e-01,106.976562
8,2026-05-26 14:57:09,0,2026-05-26 06:57:09.344818+0000,20260526,107.00,C,0.062500,0.078125,0.070312,0.078125,0.039062,22930.0,15413.0,20231.0,0.051225,0.052079,4.552418e-01,1.923118e+00,-7.146125e-02,1.579266e-02,7.146125e-02,106.976562
9,2026-05-26 14:57:09,0,2026-05-26 06:57:09.344818+0000,20260526,107.25,C,0.007812,0.015625,0.011719,NaN,0.007812,23233.0,160539.0,3361.0,0.055888,0.056914,1.124402e-01,8.504477e-01,-1.232346e-02,8.586190e-03,1.232346e-02,106.976562
10,2026-05-26 14:57:09,0,2026-05-26 06:57:09.344818+0000,20260526,107.50,C,NaN,0.007812,NaN,NaN,0.007812,0.0,2899.0,635.0,NaN,0.061903,1.653402e-02,1.673700e-01,-1.468519e-03,2.252573e-03,1.468519e-03,106.976562
11,2026-05-26 14:57:09,0,2026-05-26 06:57:09.344818+0000,20260526,107.75,C,NaN,0.007812,NaN,NaN,0.000000,0.0,160524.0,18.0,NaN,0.063816,1.070858e-03,1.411297e-02,-7.622610e-05,2.916497e-04,7.622610e-05,106.976562
12,2026-05-26 14:57:09,0,2026-05-26 06:57:09.344818+0000,20260526,108.00,C,NaN,0.007812,NaN,NaN,0.000000,0.0,317211.0,0.0,NaN,0.065151,3.296751e-05,5.316160e-04,-1.962962e-06,1.873081e-05,1.962962e-06,106.976562
13,2026-05-26 14:57:09,0,2026-05-26 06:57:09.344818+0000,20260526,108.25,C,NaN,0.007812,NaN,NaN,0.000000,0.0,353956.0,0.0,NaN,0.067319,6.794105e-07,1.254540e-05,-3.578604e-08,9.418040e-07,3.578604e-08,106.976562
14,2026-05-26 14:57:09,0,2026-05-26 06:57:09.344818+0000,20260526,108.50,C,NaN,0.007812,NaN,NaN,0.000000,0.0,360629.0,0.0,NaN,0.070559,1.244036e-08,2.501365e-07,-6.064129e-10,4.411860e-08,6.064129e-10,106.976562
15,2026-05-26 14:57:09,0,2026-05-26 06:57:09.344818+0000,20260526,108.75,C,NaN,0.007812,NaN,NaN,0.000000,0.0,360866.0,0.0,NaN,0.074839,4.855345e-10,9.935876e-09,-2.334968e-11,2.355544e-09,2.334968e-11,106.976562
16,2026-05-26 14:57:09,0,2026-05-26 06:57:09.344818+0000,20260526,105.00,P,NaN,0.007812,NaN,NaN,0.000000,0.0,355037.0,68.0,NaN,0.141192,-1.561987e-04,1.065048e-03,-2.185591e-05,4.048701e-05,2.185591e-05,106.976562
17,2026-05-26 14:57:09,0,2026-05-26 06:57:09.344818+0000,20260526,105.25,P,NaN,0.007812,NaN,NaN,0.000000,0.0,373188.0,69.0,NaN,0.128177,-2.617973e-04,1.907666e-03,-3.415755e-05,6.506176e-05,3.415755e-05,106.976562
18,2026-05-26 14:57:09,0,2026-05-26 06:57:09.344818+0000,20260526,105.50,P,NaN,0.007812,NaN,NaN,0.000000,0.0,376499.0,70.0,NaN,0.116086,-5.454007e-04,4.167303e-03,-6.748559e-05,1.255113e-04,6.748559e-05,106.976562
19,2026-05-26 14:57:09,0,2026-05-26 06:57:09.345815+0000,20260526,105.75,P,NaN,0.007812,NaN,NaN,0.000000,0.0,375687.0,916.0,NaN,0.104849,-1.384858e-03,1.086172e-02,-1.655102e-04,2.873570e-04,1.655102e-04,106.976562

features saved: ZF_FOP_Snapshot_features_cn.csv

## 高频期货价格刷新

In [ ]:
from IPython.display import clear_output, display
import pandas as pd
import time

FUTURE_REFRESH_SECONDS = 0.5
FUTURE_STREAM_SECONDS = 120

if "future_tickers" in globals():
    for old_ticker in future_tickers:
        try:
            ib.cancelMktData(old_ticker.contract)
        except Exception:
            pass
    ib.sleep(0.5)

future_tickers = []
for month in FUTURE_MONTHS:
    fut = qualify_future(ib, ROOT, month, exchange="CBOT")
    ticker = ib.reqMktData(fut, genericTickList="", snapshot=False)
    ticker._month = str(month)
    future_tickers.append(ticker)

rows_history = []
start = time.time()

while time.time() - start < FUTURE_STREAM_SECONDS:
    ib.sleep(FUTURE_REFRESH_SECONDS)

    rows = []
    ts = pd.Timestamp.now(tz="Asia/Shanghai")
    for ticker in future_tickers:
        bid = ticker.bid
        ask = ticker.ask
        last = ticker.last
        close = ticker.close
        market_price = ticker.marketPrice()

        rows.append({
            "timeChina": ts.strftime("%Y-%m-%d %H:%M:%S.%f")[:-3],
            "month": ticker._month,
            "localSymbol": ticker.contract.localSymbol,
            "bid": bid,
            "ask": ask,
            "last": last,
            "close": close,
            "marketPrice": market_price,
            "bidSize": ticker.bidSize,
            "askSize": ticker.askSize,
            "lastSize": ticker.lastSize,
        })

    future_live_df = pd.DataFrame(rows)
    rows_history.extend(rows)

    clear_output(wait=True)
    display(future_live_df)

future_price_ticks = pd.DataFrame(rows_history)
FUTURE_TICKS_CSV = Path(f"{ROOT}_Future_Live_Ticks.csv")
future_price_ticks.to_csv(FUTURE_TICKS_CSV, index=False, encoding="utf-8-sig")
print("saved:", FUTURE_TICKS_CSV)

## 9. 备选：分批并发快照

如果账户行情线数量不足，无法全量保持订阅，就用这个模式。它比保持订阅慢，但每批内部仍然是并发 market data streams。

In [ ]:
# 如需使用分批模式，先取消上一节的 streamer。
# streamer.cancel()
#
# batch_contracts = filtered_contracts if "filtered_contracts" in globals() else contracts
# df_batch = snapshot_in_batches(
#     ib,
#     batch_contracts,
#     batch_size=300,
#     wait_max_seconds=15,
#     wait_stable_seconds=2,
# )
# df_batch_features = prepare_snapshot_features(df_batch, include_chinese_columns=True)
# df_batch.to_csv(SNAPSHOT_CSV, index=False, encoding="utf-8-sig")
# FEATURES_CSV = SNAPSHOT_CSV.with_name(SNAPSHOT_CSV.stem + "_features_cn.csv")
# df_batch_features.to_csv(FEATURES_CSV, index=False, encoding="utf-8-sig")
# display(summarize_snapshot(df_batch))
# display(df_batch_features.head(20))

## 10. 查看 IB API 错误

重点看 `10197`、`354`、`420`、`100/101`。这些通常分别对应其他终端抢权限、无行情权限、节流/限速、消息速率或行情线限制。

In [ ]:
pd.DataFrame(errors).tail(30)

## 11. 清理连接

跑完一定取消 market data，不然 IB Gateway 会继续占用行情线。

In [ ]:
for name in ["streamer", "sample_streamer"]:
    obj = globals().get(name)
    if obj is not None:
        obj.cancel()

if "error_handler" in globals():
    detach_error_collector(ib, error_handler)

if ib.isConnected():
    ib.disconnect()

print("disconnected")

## 12. 可视化测试（无需 Streamlit）

把 `zf_viz.py` 里的图表函数直接在 Jupyter 里渲染。
- HTML 期权链用 `display(HTML(...))`
- Altair 图直接 `.display()` 或把变量放在 cell 末尾

**前提**：已跑过第 7/8 节拿到 `df_features`，或直接从 CSV 加载。

In [14]:
from IPython.display import display, HTML
import pandas as pd
from zf_viz import (
    build_chain_html,
    chart_iv_smile,
    chart_heatmap,
    chart_oi_bars,
    chart_flow_heatmap,
    chart_flow_by_strike,
)

# ── 数据源：优先用内存里已有的 df_features；否则从 CSV 加载 ──
if "df_features" in globals() and not df_features.empty:
    snap = df_features.copy()
    print("使用内存 df_features，行数:", len(snap))
elif "df_refresh_features" in globals() and not df_refresh_features.empty:
    snap = df_refresh_features.copy()
    print("使用内存 df_refresh_features，行数:", len(snap))
else:
    snap = pd.read_csv(FEATURES_CSV)
    print("从 CSV 加载:", FEATURES_CSV, "，行数:", len(snap))

# 统一列名到 dashboard 期望的英文列
col_map = {
    "到期日": "expiration", "行权价": "strike", "看涨看跌": "right",
    "买价": "bid", "卖价": "ask", "买卖中间价": "mid", "最新成交价": "last",
    "未平仓量": "openInterest", "模型隐含波动率": "iv",
    "Delta": "delta", "Gamma": "gamma", "Theta": "theta", "Vega": "vega",
}
for cn, en in col_map.items():
    if cn in snap.columns and en not in snap.columns:
        snap[en] = snap[cn]

for col in ["strike", "bid", "ask", "mid", "openInterest", "iv", "delta"]:
    if col in snap.columns:
        snap[col] = pd.to_numeric(snap[col], errors="coerce")
snap["expiration"] = snap["expiration"].astype(str)
snap["right"]      = snap["right"].astype(str)

expirations = sorted(snap["expiration"].dropna().unique())
print("可用到期日：", expirations[:10], "... 共", len(expirations), "个")

# ── ATM 参考价（用模型标的价中位数，或手工填）──
if "undPrice" in snap.columns:
    spot = float(pd.to_numeric(snap["undPrice"], errors="coerce").dropna().median())
elif "模型标的价" in snap.columns:
    spot = float(pd.to_numeric(snap["模型标的价"], errors="coerce").dropna().median())
else:
    spot = None
print("ATM spot:", spot)

使用内存 df_features，行数: 992
可用到期日： ['20260526', '20260527', '20260528', '20260529', '20260601', '20260602', '20260603', '20260604', '20260605', '20260608'] ... 共 16 个
ATM spot: 106.9765625

In [18]:
# ── 期权链 HTML 表格 ──────────────────────────────────────────────────────────
# 改 selected_exp 查不同到期日
selected_exp = expirations[0]
print("显示到期日：", selected_exp, "  spot:", spot)
display(HTML(build_chain_html(snap, selected_exp, spot)))

显示到期日： 20260526   spot: 106.9765625

In [19]:
# ── IV Smile + OI 柱状图 ──────────────────────────────────────────────────────
iv_chart = chart_iv_smile(snap, selected_exp)
if iv_chart:
    iv_chart.display()

oi_chart = chart_oi_bars(snap, selected_exp)
if oi_chart:
    oi_chart.display()

alt.Chart(...)

alt.Chart(...)

In [20]:
# ── 跨到期日热力图（IV / OI）────────────────────────────────────────────────
# 只看一个方向，避免图太大；改 right_filter = "P" 看看跌
right_filter = "C"
sub = snap[snap["right"] == right_filter]

iv_heatmap = chart_heatmap(sub, "iv", "IV")
if iv_heatmap:
    iv_heatmap.display()

oi_heatmap = chart_heatmap(sub, "openInterest", "OI")
if oi_heatmap:
    oi_heatmap.display()

alt.FacetChart(...)

alt.FacetChart(...)

In [ ]:
# ── Flow 散点 / 按 Strike 柱状图（需要先跑 SQLite flow 保存）───────────────
from treasury_fop_chain import load_flow_events_sqlite
from pathlib import Path

FLOW_DB = Path("data") / "zf_option_flow.sqlite"
flow = load_flow_events_sqlite(FLOW_DB, limit=5000) if FLOW_DB.exists() else pd.DataFrame()
print("flow events:", len(flow))

if not flow.empty:
    fh = chart_flow_heatmap(flow)
    if fh:
        fh.display()

    fb = chart_flow_by_strike(flow)
    if fb:
        fb.display()
else:
    print("暂无 flow 数据，先跑第 7/8 节让 Streamlit 或 refresh cell 写入 SQLite。")